/**
 * Findings chapter "14-recommended-reading" — auto-generated by
 * `scripts/port-findings-chapters.mjs` from the legacy
 * `findings/14-recommended-reading.html`. Do not hand-edit this file; rerun the
 * script after editing the legacy source. The script applies
 * mechanical JSX-safety conversions only (`class=` ->
 * `className=`, void-element self-close, kebab-case style ->
 * camelCase JSX style prop, `srcset=` -> `srcSet=`,
 * `for=` -> `htmlFor=`). Mix-comparison-player blocks are
 * additionally replaced with `<MixComparisonEmbed>` React
 * component calls (D-3-a) so the chapter audio surfaces own their
 * markup and state instead of relying on EnhancedAudioController's
 * post-hydration DOM walk.
 */
export type FindingsChapterHeading = { id: string; text: string };

/*
 * Chapter h2 headings, in document order. The D-8 within-chapter
 * TOC component (rendered by `EnhancedFindingsShell`) reads this
 * to emit `<nav aria-label="On this page">` for long chapters.
 * IDs match the values baked into the JSX below by `injectH2Ids`.
 */
export const FindingsChapter14Headings: FindingsChapterHeading[] = [
  { id: "core-himmp-publications", text: "Core HiMMP Publications" },
  { id: "foundational-journal-article", text: "Foundational Journal Article" },
  { id: "professional-production-guide", text: "Professional Production Guide" },
  { id: "further-himmp-project-outputs", text: "Further HiMMP Project Outputs" }
];

export function FindingsChapter14() {
  return (
    <main id="main-content">
<section className="chapter-hero" style={{ backgroundImage: "url('Figures/0_Cover.jpg')", backgroundSize: "cover", backgroundPosition: "center", position: "relative" }}>
      <div className="hero-overlay"></div>
      <div className="container">
        <div className="hero-content">
          <h1 className="hero-title">Chapter 14: Recommended Reading</h1>
          <p className="hero-text">Essential reading on heaviness in metal music production.</p>
        </div>
      </div>
    </section>
    <div className="chapter-section-nav">
      <div className="container">
        <h3>Navigate Chapters</h3>
        <div className="chapter-nav-buttons">
          <a href="./01-introduction.html" className="chapter-nav-button">Ch. 1</a>
          <a href="./02-producers.html" className="chapter-nav-button">Ch. 2</a>
          <a href="./03-methodology.html" className="chapter-nav-button">Ch. 3</a>
          <a href="./04-foundations.html" className="chapter-nav-button">Ch. 4</a>
          <a href="./05-naturalistic.html" className="chapter-nav-button">Ch. 5</a>
          <a href="./06-hyperreal.html" className="chapter-nav-button">Ch. 6</a>
          <a href="./07-meta-instrument.html" className="chapter-nav-button">Ch. 7</a>
          <a href="./08-drums.html" className="chapter-nav-button">Ch. 8</a>
          <a href="./09-guitars-bass.html" className="chapter-nav-button">Ch. 9</a>
          <a href="./10-spatial.html" className="chapter-nav-button">Ch. 10</a>
          <a href="./11-subjective.html" className="chapter-nav-button">Ch. 11</a>
          <a href="./12-application.html" className="chapter-nav-button">Ch. 12</a>
          <a href="./13-future.html" className="chapter-nav-button">Ch. 13</a>
          <a href="./14-recommended-reading.html" className="chapter-nav-button active">Ch. 14</a>
        </div>
      </div>
    </div>
    <section className="content-section">
      <div className="container chapter-content" style={{ "--chapter": "'14'" } as Record<string, string>}>
        <p>This guide has synthesized insights from the HiMMP research project to provide practical guidance on creating heaviness in metal production. For those seeking to deepen their understanding of the theoretical foundations, production techniques, and broader context of this research, we recommend the following essential reading.</p>

        <h2 id="core-himmp-publications">Core HiMMP Publications</h2>
        <p>The comprehensive scholarly work underlying this practical guide is available in two complementary volumes published by Routledge:</p>

        <h3>Volume 1: Theoretical Framework</h3>
        <p><strong>Herbst, Jan-Peter &amp; Mynett, Mark</strong> (2025). <em>Heaviness in Metal Music Production, Volume 1: How and Why It Works</em>. Abingdon: Routledge. DOI: <a href="https://doi.org/10.4324/9781003325727" target="_blank" rel="noopener noreferrer">10.4324/9781003325727</a></p>
        <p>This volume provides the theoretical framework and empirical foundation for understanding heaviness in metal music production. It examines the sonic, performative, structural, and affective dimensions of heaviness through detailed analysis of professional production practices, thereby establishing the conceptual basis for the naturalistic and hyperreal production philosophies explored in this guide.</p>

        <h3>Volume 2: Producer Case Studies</h3>
        <p><strong>Herbst, Jan-Peter &amp; Mynett, Mark</strong> (2025). <em>Heaviness in Metal Music Production, Volume 2: Learn from the Masters</em>. Abingdon: Routledge. DOI: <a href="https://doi.org/10.4324/9781003564089" target="_blank" rel="noopener noreferrer">10.4324/9781003564089</a></p>
        <p>Volume 2 presents in-depth case studies of the eight world-class producers featured in the HiMMP research project. Through extended interviews and detailed technical analysis of their commissioned mixes, this volume offers unprecedented insight into how leading professionals conceptualize and create heaviness across the naturalistic-hyperreal spectrum.</p>

        <h2 id="foundational-journal-article">Foundational Journal Article</h2>

        <p><strong>Herbst, Jan-Peter &amp; Smialek, Eric</strong> (2025). "'Mixed' Results: An Introduction to Analyzing Metal Production through Eight Commissioned Metal Mixes". <em>Zeitschrift der Gesellschaft für Musiktheorie</em> (Journal of the German-Speaking Society for Music Theory), 22/1. DOI: <a href="https://doi.org/10.31751/1222" target="_blank" rel="noopener noreferrer">10.31751/1222</a></p>
        <p>This peer-reviewed article introduces the methodological approach of the HiMMP project and explains how commissioned mixes from leading producers enable controlled analysis of production variables. The article demonstrates how this research method reveals the philosophical and technical diversity within professional metal production. It establishes the framework for understanding the naturalistic and hyperreal approaches detailed in this guide.</p>

        <h2 id="professional-production-guide">Professional Production Guide</h2>

        <p><strong>Mynett, Mark</strong> (2017). <em>Metal Music Manual: Producing, Engineering, Mixing, and Mastering Contemporary Heavy Music</em>. Abingdon: Routledge. DOI: <a href="https://doi.org/10.4324/9781315750071" target="_blank" rel="noopener noreferrer">10.4324/9781315750071</a></p>
        <p>This comprehensive professional guide covers all aspects of metal music production, from pre-production through mastering. Written by HiMMP co-investigator Mark Mynett, the Manual provides detailed technical instruction alongside conceptual frameworks for understanding heavy music production. It serves as an essential companion to this guide and offers extensive practical guidance on implementing the techniques and approaches discussed throughout the HiMMP research.</p>

        <h2 id="further-himmp-project-outputs">Further HiMMP Project Outputs</h2>
        <p>The HiMMP project has generated a substantial body of research outputs including journal articles, book chapters, conference presentations, and industry publications. For a complete listing of project outputs and additional recommended reading on metal music production, heaviness, and related topics, please visit our <a href="../publications.html">Publications page</a>.</p>
        <p>The Publications page includes:</p>
        <ul>
          <li><strong>Academic Publications:</strong> Peer-reviewed articles exploring specific aspects of heaviness, production aesthetics, and methodological innovations</li>
          <li><strong>Industry Publications:</strong> Practical guides and technical articles for working professionals</li>
          <li><strong>Conference Presentations:</strong> Research presentations at academic and industry conferences</li>
          <li><strong>Further Reading:</strong> Curated recommendations for foundational texts in metal studies, music production research, and audio engineering</li>
        </ul>

        <aside className="sidebar-box">
          <strong>Open Access Commitment</strong>
          <p>The HiMMP project is committed to making research accessible to both academic and professional communities. All core publications, including both Routledge volumes, are published under Creative Commons licences and are freely available for download. Visit our <a href="../publications.html">Publications page</a> for direct access to all project outputs.</p>
        </aside>

        <aside className="citation-box" aria-label="Citation and Licence">
          <strong>Citation</strong>
          <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
          <strong>Copyright &amp; Licence</strong>
          <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
        </aside>
        <div className="chapter-resources">
          <div className="container">
            <h3>Explore the Research</h3>
            <div className="resource-buttons">
              <a href="../audio.html" className="resource-button">Listen to Audio Examples</a>
              <a href="../videos.html" className="resource-button">Watch Producer Videos</a>
              <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer" className="resource-button">Download Full Dataset</a>
              <a href="../findings.html" className="resource-button">All Chapters</a>
            </div>
          </div>
        </div>

        <nav className="chapter-nav">
          <a className="prev-chapter" href="./13-future.html">← Prev: Ch. 13 Future Directions</a>
          <a className="all-chapters" href="../findings.html">Return to All Findings</a>
          <span className="next-chapter" style={{ color: "var(--medium-gray)" }}>Last Chapter</span>
        </nav>
      </div>
    </section>
  <section className="content-section">
    <div className="container">
    </div>
  </section>
    </main>
  );
}
