/**
 * Findings chapter "08-drums" — auto-generated by
 * `scripts/port-findings-chapters.mjs` from the legacy
 * `findings/08-drums.html`. Do not hand-edit this file; rerun the
 * script after editing the legacy source. The script applies
 * mechanical JSX-safety conversions only (`class=` ->
 * `className=`, void-element self-close, kebab-case style ->
 * camelCase JSX style prop, `srcset=` -> `srcSet=`,
 * `for=` -> `htmlFor=`). Mix-comparison-player blocks are
 * additionally replaced with `<MixComparisonEmbed>` React
 * component calls (D-3-a) so the chapter audio surfaces own their
 * markup and state instead of relying on EnhancedAudioController's
 * post-hydration DOM walk.
 */
import { MixComparisonEmbed } from "@/src/site/components/MixComparisonEmbed";

export type FindingsChapterHeading = { id: string; text: string };

/*
 * Chapter h2 headings, in document order. The D-8 within-chapter
 * TOC component (rendered by `EnhancedFindingsShell`) reads this
 * to emit `<nav aria-label="On this page">` for long chapters.
 * IDs match the values baked into the JSX below by `injectH2Ids`.
 */
export const FindingsChapter08Headings: FindingsChapterHeading[] = [
  { id: "sample-implementation", text: "Sample Implementation" },
  { id: "kick-drum-the-cornerstone-of-heaviness", text: "Kick Drum: The Cornerstone of Heaviness" },
  { id: "snare-drum-the-aggressive-edge", text: "Snare Drum: The Aggressive Edge" },
  { id: "toms-and-cymbals-detail-and-dimension", text: "Toms and Cymbals: Detail and Dimension" },
  { id: "dynamic-processing-strategies", text: "Dynamic Processing Strategies" },
  { id: "spatial-treatment-and-cohesion", text: "Spatial Treatment and Cohesion" }
];

export function FindingsChapter08() {
  return (
    <main id="main-content">
<section className="chapter-hero" style={{ backgroundImage: "url('Figures/0_Cover.jpg')", backgroundSize: "cover", backgroundPosition: "center", position: "relative" }}><div className="hero-overlay"></div><div className="container"><div className="hero-content"><h1 className="hero-title">Chapter 8: Drum Production</h1><p className="hero-text">The foundation of impact in heavy production.</p></div></div></section>
    <div className="chapter-section-nav">
      <div className="container">
        <h3>Navigate Chapters</h3>
        <div className="chapter-nav-buttons">
          <a href="./01-introduction.html" className="chapter-nav-button">Ch. 1</a>
          <a href="./02-producers.html" className="chapter-nav-button">Ch. 2</a>
          <a href="./03-methodology.html" className="chapter-nav-button">Ch. 3</a>
          <a href="./04-foundations.html" className="chapter-nav-button">Ch. 4</a>
          <a href="./05-naturalistic.html" className="chapter-nav-button">Ch. 5</a>
          <a href="./06-hyperreal.html" className="chapter-nav-button">Ch. 6</a>
          <a href="./07-meta-instrument.html" className="chapter-nav-button">Ch. 7</a>
          <a href="./08-drums.html" className="chapter-nav-button active">Ch. 8</a>
          <a href="./09-guitars-bass.html" className="chapter-nav-button">Ch. 9</a>
          <a href="./10-spatial.html" className="chapter-nav-button">Ch. 10</a>
          <a href="./11-subjective.html" className="chapter-nav-button">Ch. 11</a>
          <a href="./12-application.html" className="chapter-nav-button">Ch. 12</a>
          <a href="./13-future.html" className="chapter-nav-button">Ch. 13</a>
          <a href="./14-recommended-reading.html" className="chapter-nav-button">Ch. 14</a>
        </div>
      </div>
    </div>
    <section className="content-section">
      <div className="container chapter-content" style={{ "--chapter": "'8'" } as Record<string, string>}>
        <p>Unsurprisingly, drum production was found to be perhaps the most time-consuming and important element in creating heaviness: the foundation upon which everything else rests. Across all eight producers, careful attention was paid to drum processing, though approaches varied considerably in implementation. From minimalist enhancement to complete reimagining, each philosophy yielded distinct yet equally effective results.</p>

        <h2 id="sample-implementation">Sample Implementation</h2>
        <p>All producers except Andrew Scheps added samples to enhance and sculpt their drum sounds, though with remarkably varied methodologies. Interestingly, the number of samples used did not align neatly with the producers' philosophical positions; Bogren, who occupies the middle ground, used four kick samples, while hyperreal adherent Odeholm relied on just one strategically implemented sample. This disconnect suggests that the definition of a production philosophy rests on how samples are integrated within the larger production framework, not on sample usage itself.</p>
        <p>The research demonstrated clear distinctions in approach: some producers like Bogren employed samples as complementary layers that enhanced specific characteristics of the original recordings, while others such as Middleton used samples as complete replacements, crafting an entirely new drum sound that aligned with their sonic vision. Between these extremes, producers like Nordström and Exeter used selective reinforcement by adding samples only where the original recordings needed enhancement.</p>
        <p>This diversity of sampling techniques within both naturalistic and hyperreal camps demonstrates that the boundary between these philosophies manifests in how producers integrate them: whether preserving the performance's original character or engineering a new sonic identity that transcends the acoustic recording.</p>

        <div className="mix-comparison-embed" aria-label="Interactive Mix Comparison">
          <h3>Interactive Mix Comparison</h3>
          <p className="embed-intro">Compare kick and snare impact, transient design, and sample use across producers.</p>
          <MixComparisonEmbed note={"Tip: Switch while listening to compare transients."} mixes={[
        { src: "../assets/audio/HiMMP.mp3", name: "HiMMP Team", label: "HiMMP" },
        { src: "../assets/audio/Bogren.mp3", name: "Jens Bogren", label: "Bogren" },
        { src: "../assets/audio/Exeter.mp3", name: "Mike Exeter", label: "Exeter" },
        { src: "../assets/audio/Getgood.mp3", name: "Adam ‘Nolly’ Getgood", label: "Getgood" },
        { src: "../assets/audio/Middleton.mp3", name: "Josh Middleton", label: "Middleton" },
        { src: "../assets/audio/Nordstrom.mp3", name: "Fredrik Nordström", label: "Nordström" },
        { src: "../assets/audio/Odeholm.mp3", name: "Buster Odeholm", label: "Odeholm" },
        { src: "../assets/audio/Otero.mp3", name: "Dave Otero", label: "Otero" },
        { src: "../assets/audio/Scheps.mp3", name: "Andrew Scheps", label: "Scheps" }
      ]} />
        </div>

        <h4>Table 8.1: Overview of drum sample use per producer</h4>
        <table>
          <thead>
            <tr>
              <th scope="col">Producer</th>
              <th scope="col">Kick</th>
              <th scope="col">Snare</th>
              <th scope="col">Toms</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>Bogren</td><td>●●●●</td><td>●●●●</td><td>—</td></tr>
            <tr><td>Exeter</td><td>●●●●●</td><td>●</td><td>—</td></tr>
            <tr><td>Getgood</td><td>●●●●</td><td>●</td><td>—</td></tr>
            <tr><td>Middleton</td><td>●</td><td>●</td><td>●</td></tr>
            <tr><td>Nordström</td><td>●</td><td>●</td><td>●</td></tr>
            <tr><td>Odeholm</td><td>●</td><td>●</td><td>●</td></tr>
            <tr><td>Otero</td><td>●●●●●●</td><td>●●●●●</td><td>—</td></tr>
            <tr><td>Scheps</td><td>—</td><td>—</td><td>—</td></tr>
          </tbody>
        </table>
        <p><em>Note: Some producers, especially Middleton, have pre-mixed and bounced samples so that their number is understated.</em></p>

        <aside className="sidebar-box">
          <strong>Sidebar 1: Sample Integration Strategies</strong>
          <p>The research documented three distinct approaches to sample integration: replacement, reinforcement, and contextual blending. While replacement provides maximum control, reinforcement maintains the original character while enhancing impact. The most sophisticated approach, contextual blending, involves automated sample amounts across different song sections that creates a balance between natural feel and consistent power.</p>
        </aside>

        <h2 id="kick-drum-the-cornerstone-of-heaviness">Kick Drum: The Cornerstone of Heaviness</h2>
        <p>Apart from Andrew Scheps, every producer in the study employed some form of sample reinforcement on the kick drum, but with significantly different methodologies and intent:</p>
        <ul>
          <li><strong>Layered Approach:</strong> Jens Bogren employed one of the most complex techniques, using four distinct kick samples layered with the original recording. Each sample served a specific purpose: one for consistency across hits, another for attack definition, a third for "wet" character, and a fourth for what he termed 'obnoxious click' to cut through dense guitar sections. Despite this complexity, Bogren emphasized that these samples complemented rather than replaced the original recording in order to preserve its natural quality while enhancing specific characteristics.</li>
          <li><strong>Frequency-Split Method:</strong> Buster Odeholm applied a frequency-splitting technique<sup id="ref-1"><a href="#endnote-1">1</a></sup>, using a consistent one-shot sample for sub-bass frequencies and basic tone while retaining the original kick for high-frequency detail and variation. 'The human ear can't detect if low frequencies are "robotic"; we just feel them', he explained, justifying the perfect consistency in the low-end range. This hybrid approach ensures both consistent low-end impact and natural performance variation in the attack portion.</li>
          <li><strong>Contextual Reinforcement:</strong> Mike Exeter took a section-dependent approach by automating the blend between samples and the original kick throughout the song. In dense verses with fast double-kicks, he increased sample presence for definition; in sparse breakdowns, he allowed more of the natural kick to dominate. This context-specific methodology optimized the kick's presence throughout varying arrangements while maintaining a consistent overall character.</li>
        </ul>
        <p>Our research demonstrated that kick drum heaviness derives from two essential qualities:</p>
        <ul>
          <li><strong>Sub-bass impact<sup id="ref-2"><a href="#endnote-2">2</a></sup>:</strong> The physical sensation of air movement, typically centred around 55-125 Hz.</li>
          <li><strong>Attack definition<sup id="ref-3"><a href="#endnote-3">3</a></sup> and punch:</strong> The transient clarity that cuts through dense mixes, concentrated in the 3-5 kHz region.</li>
        </ul>
        <p>Each producer balanced these elements differently, but all ensured the kick maintained presence across the frequency spectrum while interacting appropriately with the bass guitar and palm-muted guitars.</p>

        <aside className="sidebar-box">
          <strong>Sidebar 2: The Phase Alignment Paradigm</strong>
          <p>Modern drum production increasingly focuses on phase relationships between microphones and instruments. While naturalistic producers typically align drum mics at recording for a cohesive kit sound, this ensure that individual hits reinforce one another rather than partially cancelling each other out, which creates a more solid and punchy foundation even before further processing. Hyperreal producers like Odeholm take this further by aligning the kick drum’s transient with bass and guitar at the sample level. In practice, this extends what was once an internal drum-kit concern to the entire low-end meta-instrument: kick, bass, and guitars are engineered to ‘fire’ as a single composite hit rather than as three loosely related events. This microscopic attention to timing creates the “wall of impact” characteristic of modern extreme metal.</p>
        </aside>

        <h2 id="snare-drum-the-aggressive-edge">Snare Drum: The Aggressive Edge</h2>
        <p>The snare treatment showed another spectrum of approaches, with producers balancing natural character against consistency and cut:</p>
        <ul>
          <li><strong>Bogren's 'Snare Smorgasbord':</strong> Jens Bogren applied the same layered philosophy to snare as he did to kick drums, with each sample serving a specific function: a 'natural and ringy' layer for fills, a 'beefy crack' sample for weight, a consistency layer for backbeats, and a transient 'spike' sample for definition in dense sections.</li>
          <li><strong>Natural Enhancement:</strong> In contrast, Mike Exeter and Andrew Scheps prioritized the original snare character and thus used minimal or no sample reinforcement. They instead applied strategic EQ and compression, along with automation, to maintain presence throughout the mix.</li>
          <li><strong>Complete Replacement:</strong> At the opposite extreme, Josh Middleton opted to replace the original snare entirely to achieve specific tonal qualities that complemented his guitar sound. This approach allowed for precise control over attack, sustain, and tone, which ensured consistency across various dynamic sections.</li>
        </ul>
        <p>The research identified specific challenges in managing snare sonics in extreme metal:</p>
        <ul>
          <li><strong>Disappearing under guitars:</strong> Every producer mentioned the phenomenon where a snare that sounds perfect in isolation becomes nearly inaudible once guitars enter the mix.</li>
          <li><strong>Consistency across tempos:</strong> Fast sections require different snare characteristics than slow sections.</li>
          <li><strong>Balance between attack and body:</strong> Too much attack creates a thin, clicking sound; too much body results in a muddy, unfocused impact.</li>
        </ul>
        <p>The solutions ranged from frequency-specific compression to enhance attack, strategic automation across song sections, and careful layering of samples to complement rather than replace the original recording.</p>

        <h2 id="toms-and-cymbals-detail-and-dimension">Toms and Cymbals: Detail and Dimension</h2>
        <p>While kick and snare received the most attention, tom and cymbal treatment offered insights about how producers approached the overall drum presentation:</p>
        <ul>
          <li><strong>Tom Replacement vs. Reinforcement:</strong> Three distinct approaches were observed for tom treatment. Middleton and Exeter chose complete replacement, using programmed MIDI and samples to achieve consistent tone and impact. Nordström took a reinforcement approach by adding samples beneath the original performances to enhance detail without sacrificing character. The remaining producers employed varying degrees of augmentation while retaining the original recordings as the primary source.</li>
          <li><strong>Cymbal Space and Control:</strong> Cymbals were generally not sample-reinforced or replaced, but producers differed in spatial treatment. Scheps positioned cymbals in a wide stereo field with natural decay. In contrast, Odeholm tightly controlled cymbal resonance through gating<sup id="ref-4"><a href="#endnote-4">4</a></sup> and aggressive EQ to prevent wash from obscuring other elements. These opposing approaches reflect broader philosophical differences: naturalistic production values space and dimension, while hyperreal approaches prioritize control and impact.</li>
        </ul>

        <h2 id="dynamic-processing-strategies">Dynamic Processing Strategies</h2>
        <p>Beyond sample reinforcement, the research documented sophisticated dynamic processing techniques that impacted perceived heaviness:</p>
        <ul>
          <li><strong>Transient Design:</strong> Several producers applied transient designers to customize the attack and sustain characteristics of drum elements independently. Middleton described using transient designers on toms to increase sustain while controlling the initial attack, which allowed them to resonate more fully in sparse sections. Getgood took this approach further by automating transient designer settings throughout different parts of the song, decreasing attack on isolated hits while increasing it during fast fills for a clearer sound.</li>
          <li><strong>Contextual Automation:</strong> Some producers frequently used automation as a valuable tool, though applied to varying extents. Most producers automated at least some drum elements to address specific arrangement challenges. Exeter's approach was particularly noteworthy: he made fine-grained adjustments to drum processing during different song sections to ensure optimal presence regardless of arrangement density. As he explained, 'These separate decisions make no sense in solo', referring to how drastically different processing might be applied to identical drum hits depending on their musical context.</li>
          <li><strong>Parallel Processing:</strong> Many producers employed parallel compression<sup id="ref-5"><a href="#endnote-5">5</a></sup> on drums by blending heavily compressed versions with the original signals to maintain both impact and natural dynamics. Scheps relied heavily on parallel processing rather than multiband compression, believing it preserved more of the drums' natural phase relationships while still providing the necessary control.</li>
        </ul>

        <h2 id="spatial-treatment-and-cohesion">Spatial Treatment and Cohesion</h2>
        <p>The final dimension of drum production involved creating appropriate spatial characteristics to support the overall mix approach:</p>
        <ul>
          <li><strong>Room Sound Implementation:</strong> Approaches to drum ambience fell along the natural-hyperreal spectrum. Scheps and Bogren employed room mics and reverb<sup id="ref-6"><a href="#endnote-6">6</a></sup> to create a three-dimensional drum sound with natural depth. Odeholm and Getgood favoured extremely controlled, minimal ambience with precisely tailored reverb processors only on specific elements. Between these extremes, Middleton and Otero used short, tight room simulations to add dimension without sacrificing impact.</li>
          <li><strong>Kit Cohesion:</strong> Regardless of sample usage, all producers emphasized the importance of the drum kit functioning as a unified instrument. Bogren used up to four different reverbs on drums, each tailored to specific elements but sharing some common space to create cohesion. Odeholm, despite heavy sample usage, ensured consistent transient characteristics across all drum elements to maintain the impression of a single performer.</li>
        </ul>
        <p>Achieving heavy drums involves balancing seemingly contradictory goals: maintaining both clarity and power, preserving character while ensuring consistency, and creating space without sacrificing impact. The most successful approaches resolved these tensions through the careful application of technology in service of musical intent rather than technical perfection for its own sake.</p>

        <div className="mix-comparison-embed" aria-label="Interactive Drum Stem Comparison">
          <h3>Isolated Drum Stems Comparison</h3>
          <p className="embed-intro">Compare isolated drum processing across producers to hear sample reinforcement, transient design, and spatial treatment in isolation.</p>
          <MixComparisonEmbed note={"Tip: Listen for differences in kick attack, snare tone, and room ambience."} mixes={[
        { src: "../assets/audio/stems/drums/himmp.mp3", name: "HiMMP Team", label: "HiMMP" },
        { src: "../assets/audio/stems/drums/bogren.mp3", name: "Jens Bogren", label: "Bogren" },
        { src: "../assets/audio/stems/drums/exeter.mp3", name: "Mike Exeter", label: "Exeter" },
        { src: "../assets/audio/stems/drums/getgood.mp3", name: "Adam 'Nolly' Getgood", label: "Getgood" },
        { src: "../assets/audio/stems/drums/middleton.mp3", name: "Josh Middleton", label: "Middleton" },
        { src: "../assets/audio/stems/drums/nordstrom.mp3", name: "Fredrik Nordström", label: "Nordström" },
        { src: "../assets/audio/stems/drums/odeholm.mp3", name: "Buster Odeholm", label: "Odeholm" },
        { src: "../assets/audio/stems/drums/otero.mp3", name: "Dave Otero", label: "Otero" },
        { src: "../assets/audio/stems/drums/scheps.mp3", name: "Andrew Scheps", label: "Scheps" }
      ]} />
        </div>

        <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>'The kick has to be number one. And kick always has to be because that's what's driving the rhythm. And that's what's moving the track forward'.</p>
            <footer>— Buster Odeholm</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Odeholm.jpg" alt="Buster Odeholm" />
          </div>
        </blockquote>
        <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>'If you start to isolate things too much, it's not going to work. A killer drum sound solo may be obliterated once the guitars come in, so you have to mix with the guitars in from the start, sculpting each component in context'.</p>
            <footer>— Jens Bogren</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Bogren.jpg" alt="Jens Bogren" />
          </div>
        </blockquote>
        <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>'Cymbal bleed is one of the things that anyone who has ever mixed a song with real drums is pulling their hair out trying to deal with'.</p>
            <footer>— Dave Otero</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Otero.jpg" alt="Dave Otero" />
          </div>
        </blockquote>

        <aside className="sidebar-box">
          <strong>Call to Action 1</strong>
          <p>Experiment with our featured producers' drum techniques by <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer">downloading the isolated drum stems from their 'In Solitude' mixes</a>. Compare how each producer balances natural tone with sample reinforcement and create your own hybrid approach that serves your music's specific needs.</p>
        </aside>
        <aside className="sidebar-box">
          <strong>Call to Action 2</strong>
          <p><a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer">Download the isolated drum multi-tracks from our research archive</a> and experiment with different degrees of sample reinforcement. Start with minimal augmentation, then gradually increase sample presence until you find the optimal balance for your taste. After that, add the remaining instruments to experience how the entire arrangement influences the drum production and vice versa.</p>
        </aside>

        <aside className="sidebar-box">
          <h3>Key Heuristics</h3>
          <ul>
            <li>Build kick heaviness from the combination of sub-bass weight and attack definition; one without the other rarely feels convincingly heavy.</li>
            <li>Decide whether samples will replace, reinforce, or subtly stabilise the live kit, and keep that role consistent across the song.</li>
            <li>Use phase alignment and transient control (on shells and between close/overhead/room mics) before reaching for heavy EQ or compression.</li>
            <li>Shape cymbals and ambience so they frame the shells and meta-instrument rather than masking them; treat cymbals as part of the rhythm, not just "top-end noise".</li>
            <li>Judge drum decisions in the full mix, especially against guitars and bass, not in solo.</li>
          </ul>
        </aside>

        <h2 id="endnotes">Endnotes</h2>
        <ol className="endnotes">
          <li id="endnote-1">Processing only certain frequencies of an instrument by removing frequencies above and below the desired range. <a className="backref" href="#ref-1">↩</a></li>
          <li id="endnote-2">Low-frequency energy that creates physical sensation and perceived weight. <a className="backref" href="#ref-2">↩</a></li>
          <li id="endnote-3">The sharpness and clarity of the initial attack transient. <a className="backref" href="#ref-3">↩</a></li>
          <li id="endnote-4">Noise gate processing that removes quiet signal components below a threshold. <a className="backref" href="#ref-4">↩</a></li>
          <li id="endnote-5">Blending heavily compressed versions with original signals. <a className="backref" href="#ref-5">↩</a></li>
          <li id="endnote-6">The simulation of multiple sound reflections that create a sense of space. <a className="backref" href="#ref-6">↩</a></li>
        </ol>

        <aside className="citation-box" aria-label="Citation and Licence">
          <strong>Citation</strong>
          <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
          <strong>Copyright &amp; Licence</strong>
          <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
        </aside>
        <div className="chapter-resources">
          <div className="container">
            <h3>Explore the Research</h3>
            <div className="resource-buttons">
              <a href="../audio.html" className="resource-button">Listen to Audio Examples</a>
              <a href="../videos.html" className="resource-button">Watch Producer Videos</a>
              <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer" className="resource-button">Download Full Dataset</a>
              <a href="../findings.html" className="resource-button">All Chapters</a>
            </div>
          </div>
        </div>

        <nav className="chapter-nav">
          <a className="prev-chapter" href="./07-meta-instrument.html">← Prev: Ch. 7 The "Meta‑Instrument"</a>
          <a className="all-chapters" href="../findings.html">Return to All Findings</a>
          <a className="next-chapter" href="./09-guitars-bass.html">Next: Ch. 9 Guitar &amp; Bass Engineering →</a>
        </nav>
      </div>
    </section>
  <section className="content-section">
    <div className="container">
    </div>
  </section>
    </main>
  );
}
