/**
 * Findings chapter "04-foundations" — auto-generated by
 * `scripts/port-findings-chapters.mjs` from the legacy
 * `findings/04-foundations.html`. Do not hand-edit this file; rerun the
 * script after editing the legacy source. The script applies
 * mechanical JSX-safety conversions only (`class=` ->
 * `className=`, void-element self-close, kebab-case style ->
 * camelCase JSX style prop, `srcset=` -> `srcSet=`,
 * `for=` -> `htmlFor=`). Mix-comparison-player blocks are
 * additionally replaced with `<MixComparisonEmbed>` React
 * component calls (D-3-a) so the chapter audio surfaces own their
 * markup and state. D-3-b retired the controller; nothing
 * DOM-walks chapter audio surfaces any more.
 */
export type FindingsChapterHeading = { id: string; text: string };

/*
 * Chapter h2 headings, in document order. The D-8 within-chapter
 * TOC component (rendered by `EnhancedFindingsShell`) reads this
 * to emit `<nav aria-label="On this page">` for long chapters.
 * IDs match the values baked into the JSX below by `injectH2Ids`.
 */
export const FindingsChapter04Headings: FindingsChapterHeading[] = [
  { id: "heaviness-a-holistic-quality", text: "Heaviness: A Holistic Quality" },
  { id: "the-multidimensional-nature-of-heaviness", text: "The Multidimensional Nature of Heaviness" },
  { id: "foundations-in-performance-and-composition", text: "Foundations in Performance and Composition" },
  { id: "a-simple-formula-slow-low-and-dense", text: "A Simple Formula: Slow, Low, and Dense" }
];

export function FindingsChapter04() {
  return (
    <main id="main-content">
<section className="chapter-hero" style={{ backgroundImage: "url('Figures/0_Cover.jpg')", backgroundSize: "cover", backgroundPosition: "center", position: "relative" }}>
      <div className="hero-overlay"></div>
      <div className="container">
        <div className="hero-content">
          <h1 className="hero-title">Chapter 4: Shared Foundations of Heaviness</h1>
          <p className="hero-text">Common ground across producers, including the "Slow, Low, and Dense" formula.</p>
        </div>
      </div>
    </section>
    <div className="chapter-section-nav">
      <div className="container">
        <h3>Navigate Chapters</h3>
        <div className="chapter-nav-buttons">
          <a href="./01-introduction.html" className="chapter-nav-button">Ch. 1</a>
          <a href="./02-producers.html" className="chapter-nav-button">Ch. 2</a>
          <a href="./03-methodology.html" className="chapter-nav-button">Ch. 3</a>
          <a href="./04-foundations.html" className="chapter-nav-button active">Ch. 4</a>
          <a href="./05-naturalistic.html" className="chapter-nav-button">Ch. 5</a>
          <a href="./06-hyperreal.html" className="chapter-nav-button">Ch. 6</a>
          <a href="./07-meta-instrument.html" className="chapter-nav-button">Ch. 7</a>
          <a href="./08-drums.html" className="chapter-nav-button">Ch. 8</a>
          <a href="./09-guitars-bass.html" className="chapter-nav-button">Ch. 9</a>
          <a href="./10-spatial.html" className="chapter-nav-button">Ch. 10</a>
          <a href="./11-subjective.html" className="chapter-nav-button">Ch. 11</a>
          <a href="./12-application.html" className="chapter-nav-button">Ch. 12</a>
          <a href="./13-future.html" className="chapter-nav-button">Ch. 13</a>
          <a href="./14-recommended-reading.html" className="chapter-nav-button">Ch. 14</a>
        </div>
      </div>
    </div>
    <section className="content-section">
      <div className="container chapter-content" style={{ "--chapter": "'4'" } as Record<string, string>}>
        <p>Despite different production philosophies, all producers share a foundational consensus on the nature of heaviness in metal:</p>

        <h2 id="heaviness-a-holistic-quality">Heaviness: A Holistic Quality</h2>
        <p>While production techniques contribute considerably, the producers emphasized that heaviness transcends pure sonics. Heavy music creates a physical reaction (body) and an emotional response (mind) through a combination of composition and performance, enhanced by production. This holistic quality explains why records like Black Sabbath's debut album remain heavy (to some listeners, at least) despite primitive production technology, while some technically perfect modern productions lack emotional impact (for some).</p>

        <h2 id="the-multidimensional-nature-of-heaviness">The Multidimensional Nature of Heaviness</h2>
        <p>While the introduction established heaviness as metal's defining quality, the research captured producers' shared understanding of its complex nature. This complexity explains why diverse subgenres, such as the brutal intensity of death metal and the lo-fi abrasiveness of black metal, can all be perceived as "heavy" despite considerable sonic differences.</p>

        <p>The producers emphasized that heaviness is a moving target, continually developing as audiences become accustomed to previously extreme sounds. This perceptual adaptation drives metal's constant innovation; what was very heavy in the 1970s might sound tame by today's standards. Heaviness tends to have the strongest effect when it either surprises the listener or breaks conventional rules, especially when performances exceed current artistic standards. For this reason, the pursuit of greater heaviness has been a constant driver of metal's development.</p>

        <h2 id="foundations-in-performance-and-composition">Foundations in Performance and Composition</h2>
        <p>The producers unanimously emphasized that high-quality performance forms the bedrock of any heavy production. Strong performances are essential for maximizing impact and punch<sup id="ref-1"><a href="#endnote-1">1</a></sup>, while weak or sloppy execution becomes more evident in clear productions, which negatively affects the listening experience. As all producers highlighted, good performances are required for achieving natural-sounding productions that maintain emotional expression and resonance.</p>
        <p>Similarly, songwriting and arrangement were considered fundamental. Several producers argued that a heavy song, if performed expressively, could retain its heaviness regardless of how it is produced. This aligns with the observation that musical progression and contrast, such as dynamic peaks and troughs, tempo variations, and rhythmic shifts, are essential to creating effective heaviness through "sonic storytelling".</p>

        <h2 id="a-simple-formula-slow-low-and-dense">A Simple Formula: Slow, Low, and Dense</h2>
        <p>Setting aside subjectivity and subgenre variations, most producers agreed on a rough formula for what they considered heavy: metal is at its heaviest when it is slow, low, and dense (see also Figure 4.1). This is the mechanism behind effective breakdowns, which typically feature half-time tempos and open space for low-end frequencies<sup id="ref-2"><a href="#endnote-2">2</a></sup> to bloom. As Andrew Scheps noted regarding the breakdown in 'In Solitude': 'That's when the track just drops and gets really heavy because you have the room in the mix'.</p>
        <p>Across all production philosophies, all producers agreed that metal requires a balance between technical precision and emotional expression, as well as between clarity and density. They also stressed the need to balance individual instrument identity with collective impact. Finding the right balance for each production remains both the challenge and the art of creating effective heaviness in metal.</p>
        <div className="figure figure-numbered">
          <img src="Figures/Fig4.1_Heaviness_Framework.png" alt="A visual breakdown of the multidimensional nature of heaviness" loading="lazy" />
          <div className="figure-caption">A visual breakdown of the multidimensional nature of heaviness.</div>
        </div>

        <aside className="sidebar-box">
          <strong>Call to Action</strong>
          <p>Before examining the various production philosophies, take time to analyze your favourite metal albums with fresh ears. Listen for how they balance the fundamental elements of heaviness, such as sonic weight, emotional intensity, performance energy, and compositional dynamics. Understanding this shared foundation will provide valuable context for appreciating the diverse approaches explored in the following chapters.</p>
        </aside>

        <aside className="sidebar-box">
          <h3>Key Heuristics</h3>
          <ul>
            <li>Think of heaviness as holistic: it must work physically (body), emotionally (mind), and structurally (song and performance).</li>
            <li>Use the 'Slow, Low, and Dense' triad as a checklist, but always balance it against clarity, articulation, and musical intent.</li>
            <li>Aim for a dynamic balance between density and definition: too much of either undermines perceived heaviness.</li>
            <li>Remember that heaviness often comes from contrast (sections that hit harder against something lighter), not from maxing out intensity at all times.</li>
          </ul>
        </aside>

        <h2 id="endnotes">Endnotes</h2>
        <ol className="endnotes">
          <li id="endnote-1">Characterized by clear transients and a pronounced attack phase that conveys a feeling of energy. <a className="backref" href="#ref-1">↩</a></li>
          <li id="endnote-2">The bass area of the frequency spectrum. <a className="backref" href="#ref-2">↩</a></li>
        </ol>

        <aside className="citation-box" aria-label="Citation and Licence">
          <strong>Citation</strong>
          <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
          <strong>Copyright &amp; Licence</strong>
          <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
        </aside>
        <div className="chapter-resources">
          <div className="container">
            <h3>Explore the Research</h3>
            <div className="resource-buttons">
              <a href="../audio.html" className="resource-button">Listen to Audio Examples</a>
              <a href="../videos.html" className="resource-button">Watch Producer Videos</a>
              <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer" className="resource-button">Download Full Dataset</a>
              <a href="../findings.html" className="resource-button">All Chapters</a>
            </div>
          </div>
        </div>

        <nav className="chapter-nav">
          <a className="prev-chapter" href="./03-methodology.html">← Prev: Ch. 3 The Controlled Experiment</a>
          <a className="all-chapters" href="../findings.html">Return to All Findings</a>
          <a className="next-chapter" href="./05-naturalistic.html">Next: Ch. 5 The Naturalistic School →</a>
        </nav>
      </div>
    </section>
  <section className="content-section">
    <div className="container">
    </div>
  </section>
    </main>
  );
}
