/**
 * Findings chapter "07-meta-instrument" — auto-generated by
 * `scripts/port-findings-chapters.mjs` from the legacy
 * `findings/07-meta-instrument.html`. Do not hand-edit this file; rerun the
 * script after editing the legacy source. The script applies
 * mechanical JSX-safety conversions only (`class=` ->
 * `className=`, void-element self-close, kebab-case style ->
 * camelCase JSX style prop, `srcset=` -> `srcSet=`,
 * `for=` -> `htmlFor=`). Mix-comparison-player blocks are
 * additionally replaced with `<MixComparisonEmbed>` React
 * component calls (D-3-a) so the chapter audio surfaces own their
 * markup and state. D-3-b retired the controller; nothing
 * DOM-walks chapter audio surfaces any more.
 */
import { MixComparisonEmbed } from "@/src/site/components/MixComparisonEmbed";

export type FindingsChapterHeading = { id: string; text: string };

/*
 * Chapter h2 headings, in document order. The D-8 within-chapter
 * TOC component (rendered by `EnhancedFindingsShell`) reads this
 * to emit `<nav aria-label="On this page">` for long chapters.
 * IDs match the values baked into the JSX below by `injectH2Ids`.
 */
export const FindingsChapter07Headings: FindingsChapterHeading[] = [
  { id: "conventional-vs-meta-instrument-mixing", text: "Conventional vs. Meta-Instrument Mixing" },
  { id: "technical-implementation", text: "Technical Implementation" },
  { id: "the-physics-of-unity", text: "The Physics of Unity" },
  { id: "spectral-and-spatial-distribution", text: "Spectral and Spatial Distribution" },
  { id: "variations-across-production-philosophies", text: "Variations Across Production Philosophies" },
  { id: "impact-on-heaviness", text: "Impact on Heaviness" }
];

export function FindingsChapter07() {
  return (
    <main id="main-content">
<section className="chapter-hero" style={{ backgroundImage: "url('Figures/0_Cover.jpg')", backgroundSize: "cover", backgroundPosition: "center", position: "relative" }}>
      <div className="hero-overlay"></div>
      <div className="container">
        <div className="hero-content">
          <h1 className="hero-title">Chapter 7: The "Meta-Instrument" Concept</h1>
          <p className="hero-text">Treating kick, bass, and guitars as a single, unified sonic entity.</p>
        </div>
      </div>
    </section>
    <div className="chapter-section-nav">
      <div className="container">
        <h3>Navigate Chapters</h3>
        <div className="chapter-nav-buttons">
          <a href="./01-introduction.html" className="chapter-nav-button">Ch. 1</a>
          <a href="./02-producers.html" className="chapter-nav-button">Ch. 2</a>
          <a href="./03-methodology.html" className="chapter-nav-button">Ch. 3</a>
          <a href="./04-foundations.html" className="chapter-nav-button">Ch. 4</a>
          <a href="./05-naturalistic.html" className="chapter-nav-button">Ch. 5</a>
          <a href="./06-hyperreal.html" className="chapter-nav-button">Ch. 6</a>
          <a href="./07-meta-instrument.html" className="chapter-nav-button active">Ch. 7</a>
          <a href="./08-drums.html" className="chapter-nav-button">Ch. 8</a>
          <a href="./09-guitars-bass.html" className="chapter-nav-button">Ch. 9</a>
          <a href="./10-spatial.html" className="chapter-nav-button">Ch. 10</a>
          <a href="./11-subjective.html" className="chapter-nav-button">Ch. 11</a>
          <a href="./12-application.html" className="chapter-nav-button">Ch. 12</a>
          <a href="./13-future.html" className="chapter-nav-button">Ch. 13</a>
          <a href="./14-recommended-reading.html" className="chapter-nav-button">Ch. 14</a>
        </div>
      </div>
    </div>
    <section className="content-section">
      <div className="container chapter-content" style={{ "--chapter": "'7'" } as Record<string, string>}>
        <p>One of the most significant insights to result from the research was the concept of the <strong>"meta-instrument"</strong>: a production approach that reframes how instruments interact in heavy music. This concept, while particularly prominent in hyperreal production, has influenced metal mixing across the spectrum and represents a paradigm shift in how engineers conceptualize heaviness.</p>

        <h2 id="conventional-vs-meta-instrument-mixing">Conventional vs. Meta-Instrument Mixing</h2>

        <p><strong>Traditional Approach: Each instrument as a separate entity.</strong></p>
        <ul>
          <li>Each instrument occupies its own frequency space and stereo position.</li>
          <li>Clear separation between elements (kick handles sub-bass, bass guitar covers bass and low-mids, guitars dominate the midrange).</li>
          <li>Focus on distinction between elements for clarity.</li>
        </ul>

        <p><strong>Meta-Instrument Approach: Instruments as components of a unified force.</strong></p>
        <ul>
          <li>Guitars, bass, and kick drum function as parts of a single massive sound.</li>
          <li>Intentional frequency overlap with careful phase relationships.</li>
          <li>Coordinated dynamic behaviour across instrument groups.</li>
          <li>Focus on collective impact rather than individual clarity.</li>
        </ul>

        <h2 id="technical-implementation">Technical Implementation</h2>
        <p>Implementing the meta-instrument approach requires specific technical strategies:</p>
        <ul>
          <li><strong>Transient Alignment:</strong> The foundation of the meta-instrument concept is precise rhythmic alignment between instruments. In other words, the same kind of timing care that traditionally applied within the drum kit is now applied across kick, bass, and guitars. Odeholm's sample-level editing approach (detailed in <a href="./06-hyperreal.html">Chapter 6</a>) represents the extreme application of this principle. Even slightly more conservative producers like Getgood and Otero emphasize the importance of aligned attacks for maximum heaviness, though with less microscopic attention to waveform alignment.</li>
          <li><strong>Complementary Frequency Allocation:</strong> Rather than assigning completely separate frequency ranges and spatial positions to each instrument, meta-instrument mixing creates intentional overlaps while ensuring phase coherence<sup id="ref-1"><a href="#endnote-1">1</a></sup>. Josh Middleton demonstrated this approach by high-passing guitars at just 70 Hz<sup id="ref-2"><a href="#endnote-2">2</a></sup>, which allows them to carry significant low-end energy. He simultaneously cut around 180 Hz and boosted the bass guitar at 190 Hz to create a complementary frequency relationship.</li>
          <li><strong>Unified Dynamic Behaviour:</strong> Meta-instrument production often employs synchronized dynamics processing across multiple instruments. Odeholm's approach of sidechaining<sup id="ref-3"><a href="#endnote-3">3</a></sup> both bass and guitars to the kick drum ensures the entire instrument group "breathes" together, ducking<sup id="ref-4"><a href="#endnote-4">4</a></sup> in unison when the kick hits and swelling back collectively. This coordinated movement enhances the perception of a single entity rather than separate instruments.</li>
          <li><strong>Interconnected Processing Chains:</strong> The approach often integrates signal paths between instruments that traditionally would be processed independently. For example, several producers mentioned using a send from the kick drum to trigger a specific distortion characteristic on the bass or linking compressors across instrument groups. These interconnections create a cohesive texture where instruments enhance rather than compete with each other.</li>
        </ul>

        <h2 id="the-physics-of-unity">The Physics of Unity</h2>
        <p>The meta-instrument concept has acoustic foundations: when waveforms align in phase, they create constructive interference and double their physical power. This matters in practice because the listener experiences that constructive interference as a tighter, more solid low-end ‘hit’ (i.e. a sensation of weight and punch) even if the overall meter level has not changed dramatically. When kick, bass, and guitar transients align perfectly, they create a pressure wave far greater than the sum of individual instruments.</p>

        <h2 id="spectral-and-spatial-distribution">Spectral and Spatial Distribution</h2>
        <p>The meta-instrument concept manifests in unconventional approaches to both frequency allocation and stereo positioning:</p>
        <ul>
          <li><strong>Frequency Integration:</strong> While traditional mixing often high-passes guitars around 100 Hz to make room for bass, meta-instrument mixing might allow guitars to extend down to 60 Hz while carefully controlling their relationship with the bass guitar through phase alignment and dynamic processing. This creates an integrated spectrum where the listener cannot easily distinguish which instrument is generating specific low frequencies (Figures 7.1–7.3).</li>
        </ul>

        <div className="figure figure-numbered">
          <img src="Figures/Fig7.1_Kick=Bass.png" alt="Overlapping frequencies reflective of the meta-instrument concept in the mixes of Josh Middleton and Buster Odeholm" loading="lazy" />
          <div className="figure-caption">Overlapping frequencies reflective of the meta-instrument concept in the mixes of Josh Middleton and Buster Odeholm.</div>
        </div>

        <div className="figure figure-numbered">
          <img src="Figures/Fig7.2_Bass_under_Kick.png" alt="Positioning bass under the kick in the mixes of Mike Exeter and Adam Getgood" loading="lazy" />
          <div className="figure-caption">Positioning bass under the kick in the mixes of Mike Exeter and Adam Getgood. This frequency allocation was dominant before the proliferation of kick-trigger technology.</div>
        </div>

        <div className="figure figure-numbered">
          <img src="Figures/Fig7.3_Kick_under_Bass.png" alt="Placement of kick under bass, which is most common in contemporary productions" loading="lazy" />
          <div className="figure-caption">Placement of kick under bass, which is most common in contemporary productions.</div>
        </div>

        <ul>
          <li><strong>Spatial Reconfiguration:</strong> Odeholm's approach of panning<sup id="ref-5"><a href="#endnote-5">5</a></sup> a guitar track in the centre while spreading the bass across the stereo field represents a radical departure from traditional placement (Figure 7.4). This technique distributes the meta-instrument across the entire stereo field while maintaining its unified impact to create what Getgood describes as a 'floor-to-ceiling sound'.</li>
        </ul>

        <div className="figure figure-numbered">
          <img src="Figures/Fig7.4_Widened_bass.png" alt="Widened stereo bass in the mixes of Buster Odeholm and Jens Bogren" loading="lazy" />
          <div className="figure-caption">Widened stereo bass in the mixes of Buster Odeholm and Jens Bogren.</div>
        </div>

        <div className="mix-comparison-embed" aria-label="Interactive Mix Comparison">
          <h3>Interactive Mix Comparison</h3>
          <p className="embed-intro">Listen for the meta-instrument effect by switching producers mid-playback.</p>
          <MixComparisonEmbed note={"Tip: Switching preserves the current play position."} mixes={[
        { src: "../assets/audio/HiMMP.mp3", name: "HiMMP Team", label: "HiMMP" },
        { src: "../assets/audio/Bogren.mp3", name: "Jens Bogren", label: "Bogren" },
        { src: "../assets/audio/Exeter.mp3", name: "Mike Exeter", label: "Exeter" },
        { src: "../assets/audio/Getgood.mp3", name: "Adam ‘Nolly’ Getgood", label: "Getgood" },
        { src: "../assets/audio/Middleton.mp3", name: "Josh Middleton", label: "Middleton" },
        { src: "../assets/audio/Nordstrom.mp3", name: "Fredrik Nordström", label: "Nordström" },
        { src: "../assets/audio/Odeholm.mp3", name: "Buster Odeholm", label: "Odeholm" },
        { src: "../assets/audio/Otero.mp3", name: "Dave Otero", label: "Otero" },
        { src: "../assets/audio/Scheps.mp3", name: "Andrew Scheps", label: "Scheps" }
      ]} />
        </div>

        <h2 id="variations-across-production-philosophies">Variations Across Production Philosophies</h2>
        <p>Now that you have explored the interactive mix comparison, it is important to note that while the meta-instrument concept reaches its logical extreme in hyperreal production, elements of this approach appear across the philosophical spectrum:</p>
        <ul>
          <li><strong>Naturalistic Implementation:</strong> Even Exeter, the most traditional producer in the study, demonstrated meta-instrument thinking through his complementary EQ choices for guitar and bass and his strategic automation of elements to work together in specific sections. Rather than enforcing rigid alignment, he created natural cohesion through careful balancing and tonal matching.</li>
          <li><strong>Moderate Application:</strong> Producers like Bogren and Scheps employed partial meta-instrument techniques, particularly in how they approached the kick and bass relationship. Bogren's practice of sidechaining the bass not just to the kick but also to the toms demonstrates systematic thinking about how these elements should function together as a unified rhythmic foundation.</li>
          <li><strong>Full Integration:</strong> At the furthest extreme, Odeholm treated the entire instrument section as essentially one massive synthesizer, with each component carefully tuned to contribute to a singular sonic event rather than stand as individual instruments.</li>
        </ul>

        <h2 id="impact-on-heaviness">Impact on Heaviness</h2>
        <p>The meta-instrument concept addresses what many producers identified as essential to heaviness: the sensation of being confronted by an overwhelming force rather than discrete elements. By engineering instruments to function as a unified entity, producers create what Getgood describes as a mechanical yet musical quality: a sound that exceeds what humans could physically produce while maintaining musical coherence.</p>
        <p>This approach particularly excels at creating the 'freight train rolling over you' type of heaviness that Josh Middleton described. This is a sensation of density and weight that physically impacts the listener. When implemented effectively, the meta-instrument creates a sound that physically embodies heaviness rather than merely suggesting it.</p>
        <p>The meta-instrument concept raises questions about the nature of instrumental identity in modern production. While traditional approaches preserve the distinct character of each instrument, meta-instrument mixing deliberately blurs these boundaries in service of a greater sonic impact. This represents a fundamental shift from documenting a performance to engineering an experience. It is a development that continues to reshape how heaviness is conceived and created in contemporary metal.</p>

        <aside className="sidebar-box">
          <strong>Sidebar: From Record to Performance</strong>
          <p>The meta-instrument approach presents unique challenges for live performance. Bands employing these production techniques, including Odeholm-led Humanity's Last Breath, often use backing tracks, sample triggers, and synchronized lighting to recreate the unified impact of their recorded sound on stage.</p>
        </aside>

        <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>'Get the band to sound like one unit... one big tank going forward'.</p>
            <footer>— Fredrik Nordström</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Nordstrom.jpg" alt="Fredrik Nordström" />
          </div>
        </blockquote>

        <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>'That's when all the transients have to be at the same point. The guitar, bass, and kick drum have to hit exactly at the same time and be in phase, which is like samples of timing difference'.</p>
            <footer>— Buster Odeholm</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Odeholm.jpg" alt="Buster Odeholm" />
          </div>
        </blockquote>

        <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>'A lot of people say kick below or above bass or bass above or below kick. I never really think about it like that; I let the sources guide me'.</p>
            <footer>— Dave Otero</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Otero.jpg" alt="Dave Otero" />
          </div>
        </blockquote>

        <aside className="sidebar-box">
          <strong>Call to Action</strong>
          <p>Create three versions of the 'In Solitude' mix implementing different degrees of meta-instrument integration: one using traditional separation-focused techniques, another employing moderate meta-instrument concepts (primarily through frequency relationships), and a third fully embracing the hyperreal meta-instrument approach with complete transient alignment and unified processing.</p>
        </aside>

        <aside className="sidebar-box">
          <h3>Key Heuristics</h3>
          <ul>
            <li>Treat kick, bass, and rhythm guitars as one interlocking meta-instrument rather than three independent sources.</li>
            <li>Align timing and transients across the low-end elements first; only then adjust tone and effects.</li>
            <li>Carve frequency ranges so each component has a clear primary job (e.g. sub-weight vs low-mid punch vs upper-mid articulation) within the meta-instrument.</li>
            <li>Automate balances and processing by riff and section, not only by channel, so the meta-instrument behaves musically with the arrangement.</li>
          </ul>
        </aside>

        <h2 id="endnotes">Endnotes</h2>
        <ol className="endnotes">
          <li id="endnote-1">Alignment of audio signals to prevent cancellation. <a className="backref" href="#ref-1">↩</a></li>
          <li id="endnote-2">Using a high-pass filter that removes frequencies below 70 Hz. <a className="backref" href="#ref-2">↩</a></li>
          <li id="endnote-3">Triggering effects on one track based on the volume of another track. <a className="backref" href="#ref-3">↩</a></li>
          <li id="endnote-4">Lowering volume when another sound exceeds a threshold. <a className="backref" href="#ref-4">↩</a></li>
          <li id="endnote-5">Controlling the position of a sound image between stereo speakers. <a className="backref" href="#ref-5">↩</a></li>
        </ol>

        <aside className="citation-box" aria-label="Citation and Licence">
          <strong>Citation</strong>
          <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
          <strong>Copyright &amp; Licence</strong>
          <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
        </aside>
        <div className="chapter-resources">
          <div className="container">
            <h3>Explore the Research</h3>
            <div className="resource-buttons">
              <a href="../audio.html" className="resource-button">Listen to Audio Examples</a>
              <a href="../videos.html" className="resource-button">Watch Producer Videos</a>
              <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer" className="resource-button">Download Full Dataset</a>
              <a href="../findings.html" className="resource-button">All Chapters</a>
            </div>
          </div>
        </div>

        <nav className="chapter-nav">
          <a className="prev-chapter" href="./06-hyperreal.html">← Prev: Ch. 6 The Hyperreal School</a>
          <a className="all-chapters" href="../findings.html">Return to All Findings</a>
          <a className="next-chapter" href="./08-drums.html">Next: Ch. 8 Drum Production →</a>
        </nav>
      </div>
    </section>
  <section className="content-section">
    <div className="container">
    </div>
  </section>
    </main>
  );
}
