/**
 * Findings chapter "09-guitars-bass" — auto-generated by
 * `scripts/port-findings-chapters.mjs` from the legacy
 * `findings/09-guitars-bass.html`. Do not hand-edit this file; rerun the
 * script after editing the legacy source. The script applies
 * mechanical JSX-safety conversions only (`class=` ->
 * `className=`, void-element self-close, kebab-case style ->
 * camelCase JSX style prop, `srcset=` -> `srcSet=`,
 * `for=` -> `htmlFor=`). Mix-comparison-player blocks are
 * additionally replaced with `<MixComparisonEmbed>` React
 * component calls (D-3-a) so the chapter audio surfaces own their
 * markup and state. D-3-b retired the controller; nothing
 * DOM-walks chapter audio surfaces any more.
 */
import { MixComparisonEmbed } from "@/src/site/components/MixComparisonEmbed";

export type FindingsChapterHeading = { id: string; text: string };

/*
 * Chapter h2 headings, in document order. The D-8 within-chapter
 * TOC component (rendered by `EnhancedFindingsShell`) reads this
 * to emit `<nav aria-label="On this page">` for long chapters.
 * IDs match the values baked into the JSX below by `injectH2Ids`.
 */
export const FindingsChapter09Headings: FindingsChapterHeading[] = [
  { id: "guitar-tone-development", text: "Guitar Tone Development" },
  { id: "bass-guitar-processing", text: "Bass Guitar Processing" },
  { id: "practical-implementation", text: "Practical Implementation" }
];

export function FindingsChapter09() {
  return (
    <main id="main-content">
<section className="chapter-hero" style={{ backgroundImage: "url('Figures/0_Cover.jpg')", backgroundSize: "cover", backgroundPosition: "center", position: "relative" }}>
      <div className="hero-overlay"></div>
      <div className="container">
        <div className="hero-content">
          <h1 className="hero-title">Chapter 9: Guitar &amp; Bass Engineering</h1>
          <p className="hero-text">Low-end management, dynamic EQ, and the wall of sound.</p>
        </div>
      </div>
    </section>
    <div className="chapter-section-nav">
      <div className="container">
        <h3>Navigate Chapters</h3>
        <div className="chapter-nav-buttons">
          <a href="./01-introduction.html" className="chapter-nav-button">Ch. 1</a>
          <a href="./02-producers.html" className="chapter-nav-button">Ch. 2</a>
          <a href="./03-methodology.html" className="chapter-nav-button">Ch. 3</a>
          <a href="./04-foundations.html" className="chapter-nav-button">Ch. 4</a>
          <a href="./05-naturalistic.html" className="chapter-nav-button">Ch. 5</a>
          <a href="./06-hyperreal.html" className="chapter-nav-button">Ch. 6</a>
          <a href="./07-meta-instrument.html" className="chapter-nav-button">Ch. 7</a>
          <a href="./08-drums.html" className="chapter-nav-button">Ch. 8</a>
          <a href="./09-guitars-bass.html" className="chapter-nav-button active">Ch. 9</a>
          <a href="./10-spatial.html" className="chapter-nav-button">Ch. 10</a>
          <a href="./11-subjective.html" className="chapter-nav-button">Ch. 11</a>
          <a href="./12-application.html" className="chapter-nav-button">Ch. 12</a>
          <a href="./13-future.html" className="chapter-nav-button">Ch. 13</a>
          <a href="./14-recommended-reading.html" className="chapter-nav-button">Ch. 14</a>
        </div>
      </div>
    </div>
    <section className="content-section">
      <div className="container chapter-content" style={{ "--chapter": "'9'" } as Record<string, string>}>
        <p>Guitar and bass processing form the tonal centre of metal production, as they occupy the majority of the frequency spectrum and define the music's textural character. Our research documented different approaches to engineering these instruments, with specific techniques that varied dramatically between producers, yet shared common conceptual foundations.</p>

        <h2 id="guitar-tone-development">Guitar Tone Development</h2>
        <p>All producers agreed that guitar heaviness begins at the source, with appropriate amplification, cabinet selection, and microphone placement. In the 'In Solitude' mix, all producers but Scheps and Exeter reamped the provided DI tracks or used amplifier simulation<sup id="ref-1"><a href="#endnote-1">1</a></sup> to craft their signature high-gain sound, rather than working with pre-recorded guitar tracks (Figure 9.1). This approach emphasizes a central principle: in metal production, the foundational guitar tone must be established before mixing begins.</p>

        <div className="figure figure-numbered">
          <img src="Figures/Fig9.1_Amp1.png" alt="Virtual amplifier simulation in Middleton's mix, using his signature STL Tonality amplifier" loading="lazy" />
          <img src="Figures/Fig9.1_Amp2.png" alt="Virtual amplifier simulation - additional view" loading="lazy" />
          <div className="figure-caption">Virtual amplifier simulation in Middleton's mix, using his signature STL Tonality amplifier.</div>
        </div>

        <p>Several key approaches to guitar processing were observed:</p>
        <ul>
          <li><strong>Dynamic Low-End Management:</strong> Most producers applied multiband compression or dynamic EQ<sup id="ref-2"><a href="#endnote-2">2</a></sup> on guitars, which targets frequencies below 200 Hz. This technique, used by producers like Fredrik Nordström as early as in the early 1990s, addresses a great challenge in heavy music: palm-muted guitar creates overwhelming low-frequency energy that can mask<sup id="ref-3"><a href="#endnote-3">3</a></sup> bass guitar and kick drum.</li>
        </ul>

        <p>'I would compress the bass frequencies of the guitar whenever the guitarist palm-mutes and causes a low-end build-up', Nordström explained. 'In practice, I set a multiband compressor on guitars that kicks in around &lt;200 Hz whenever needed to reduce ~2-3 dB on chugging parts'. This selective compression maintains guitar heaviness while creating space for other elements to cut through.</p>

        <aside className="sidebar-box">
          <strong>Sidebar: Understanding the Chugging Problem</strong>
          <p>Palm‑muted passages create substantial low‑frequency energy that can mask bass and kick. Solutions range from frequency‑specific dynamic EQ to sidechain networks. Controlling this interaction is essential for clarity and power in modern metal production.</p>
        </aside>
        <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>"I try to get rid of bass in the rhythm guitars; that's just like the bass's own area. That's where it is together with the bass drum. And if they work together, you can hear the bass and also hear the bass drum and punch in the bass drum."</p>
            <footer>— Fredrik Nordström</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Nordstrom.jpg" alt="Fredrik Nordström" />
          </div>
        </blockquote>


        <ul>
          <li><strong>Frequency Allocation Philosophy:</strong> Building on the meta-instrument frequency relationships described in <a href="./07-meta-instrument.html">Chapter 7</a>, several producers challenged conventional high-pass filtering<sup id="ref-4"><a href="#endnote-4">4</a></sup> approaches. Middleton high-passed at only 70 Hz, while Getgood filtered at just 60 Hz, allowing guitars to contribute substantially to perceived low-end heaviness.</li>
        </ul>

        <p>As Andrew Scheps noted, 'In modern metal, guitars often act as much in the low-end as the bass does because bass is distorted and thus has a lot of mid content... their low-end is being borrowed by the guitars'. This inversion of traditional frequency allocation creates the characteristic "wall of sound" effect where guitars and bass blend into a unified low-end mass rather than occupying separate spectral regions.</p>

        <ul>
          <li><strong>Width Enhancement Strategies:</strong> Stereo guitar treatment revealed another spectrum of approaches. All producers double-tracked rhythm guitars (panning one take left, another right), but with significant variations in implementation. All producers but Odeholm employed quad-tracking<sup id="ref-5"><a href="#endnote-5">5</a></sup> for enhanced thickness. Getgood and Middleton applied psychoacoustic widening techniques<sup id="ref-6"><a href="#endnote-6">6</a></sup> to create a stereo spread that exceeded the natural width of panned guitars. Exeter and Scheps achieved similar width through EQ differentiation: they applied slightly different equalization to left and right guitar channels, creating a perceived width enhancement without dedicated widening processors (Figures 9.2–9.3).</li>
        </ul>

        <div className="figure figure-numbered">
          <img src="Figures/Fig9.2_Symmetrical_Guitar.png" alt="Stereo-widened, symmetrical guitar panning in the mixes of Adam Getgood and Josh Middleton" loading="lazy" />
          <div className="figure-caption">Stereo-widened, symmetrical guitar panning in the mixes of Adam Getgood and Josh Middleton.</div>
        </div>

        <div className="figure figure-numbered">
          <img src="Figures/Fig9.3_Asymmetrical_Guitar.png" alt="Different EQ settings in the mixes of Mike Exeter and Andrew Scheps, creating an asymmetrical stereo impression comparably wide to other symmetrical mixes" loading="lazy" />
          <div className="figure-caption">Different EQ settings in the mixes of Mike Exeter and Andrew Scheps, creating an asymmetrical stereo impression comparably wide to other symmetrical mixes.</div>
        </div>

        <p>Our analysis showed that distinct EQ treatment between channels could create a stereo image as expansive as specialized widening techniques and offer a more transparent alternative to psychoacoustic processing.</p>

        <div className="mix-comparison-embed" aria-label="Interactive Mix Comparison">
          <h3>Interactive Mix Comparison</h3>
          <p className="embed-intro">A/B low-end management and stereo width strategies across producers.</p>
          <MixComparisonEmbed note={"Tip: Focus on palm-muted passages and bass definition."} mixes={[
        { src: "../assets/audio/HiMMP.mp3", name: "HiMMP Team", label: "HiMMP" },
        { src: "../assets/audio/Bogren.mp3", name: "Jens Bogren", label: "Bogren" },
        { src: "../assets/audio/Exeter.mp3", name: "Mike Exeter", label: "Exeter" },
        { src: "../assets/audio/Getgood.mp3", name: "Adam 'Nolly' Getgood", label: "Getgood" },
        { src: "../assets/audio/Middleton.mp3", name: "Josh Middleton", label: "Middleton" },
        { src: "../assets/audio/Nordstrom.mp3", name: "Fredrik Nordström", label: "Nordström" },
        { src: "../assets/audio/Odeholm.mp3", name: "Buster Odeholm", label: "Odeholm" },
        { src: "../assets/audio/Otero.mp3", name: "Dave Otero", label: "Otero" },
        { src: "../assets/audio/Scheps.mp3", name: "Andrew Scheps", label: "Scheps" }
      ]} waveformHeights={[69, 40, 59, 50, 46, 67, 62, 84, 62, 85, 76, 72, 90, 78, 73, 92, 78, 65, 92, 80, 92, 70, 92, 66, 88, 69, 81, 73, 69, 86, 68, 92, 83, 77, 89, 76, 62, 60, 74, 92, 51, 79, 59, 46, 79, 53, 78, 72]} />
        </div>

        <div className="mix-comparison-embed" aria-label="Interactive Guitar Stem Comparison">
          <h3>Isolated Guitar Stems Comparison</h3>
          <p className="embed-intro">Compare isolated guitar processing to hear stereo width, low-end management, and tonal characteristics across producers.</p>
          <MixComparisonEmbed note={"Tip: Listen for palm-mute control, stereo width, and frequency allocation."} mixes={[
        { src: "../assets/audio/stems/guitars/himmp.mp3", name: "HiMMP Team", label: "HiMMP" },
        { src: "../assets/audio/stems/guitars/bogren.mp3", name: "Jens Bogren", label: "Bogren" },
        { src: "../assets/audio/stems/guitars/exeter.mp3", name: "Mike Exeter", label: "Exeter" },
        { src: "../assets/audio/stems/guitars/getgood.mp3", name: "Adam 'Nolly' Getgood", label: "Getgood" },
        { src: "../assets/audio/stems/guitars/middleton.mp3", name: "Josh Middleton", label: "Middleton" },
        { src: "../assets/audio/stems/guitars/nordstrom.mp3", name: "Fredrik Nordström", label: "Nordström" },
        { src: "../assets/audio/stems/guitars/odeholm.mp3", name: "Buster Odeholm", label: "Odeholm" },
        { src: "../assets/audio/stems/guitars/otero.mp3", name: "Dave Otero", label: "Otero" },
        { src: "../assets/audio/stems/guitars/scheps.mp3", name: "Andrew Scheps", label: "Scheps" }
      ]} waveformHeights={[65, 47, 66, 46, 51, 51, 67, 82, 58, 86, 74, 73, 72, 71, 91, 66, 92, 88, 75, 68, 75, 90, 92, 74, 74, 84, 92, 90, 92, 92, 81, 85, 67, 92, 83, 69, 77, 80, 56, 87, 75, 73, 62, 83, 48, 51, 45, 63]} />
        </div>

        <h2 id="bass-guitar-processing">Bass Guitar Processing</h2>
        <p>Bass treatment varied considerably between producers, which reflects different conceptual approaches to its role in the meta-instrument:</p>
        <ul>
          <li><strong>Extreme Dynamic Control:</strong> All producers applied substantial compression to bass but with varying philosophies. Bogren, Getgood, and Middleton employed aggressive limiting<sup id="ref-7"><a href="#endnote-7">7</a></sup> and multiband compression to create what Odeholm described as a 'sausage of low-end', an extremely consistent dynamic profile where every note maintains identical power regardless of playing dynamics. This approach ensures the bass foundation remains stable throughout various performance techniques.</li>
        </ul>

        <p>In contrast, Exeter and Scheps exercised more restraint by using automation to manage dynamics rather than heavy compression. 'I rode the fader on the combined bass signal to manage its dynamics, preserving the natural tone', Exeter explained, maintaining more of the original performance character.</p>

        <ul>
          <li><strong>Split-Band Distortion:</strong> Bass distortion techniques offered a valuable insight into frequency management. Most producers applied distortion selectively to mid and high frequencies while keeping low frequencies relatively clean. Bogren and Middleton exemplified this approach by distorting only the upper harmonics<sup id="ref-8"><a href="#endnote-8">8</a></sup> to maintain clarity in the fundamental range.</li>
        </ul>

        <p>Odeholm, however, challenged convention by applying 'heavy distortion across the entire bass spectrum', considering it essential for consistency. This technique requires exceptional control to avoid creating mud, but when executed correctly, it creates a bass tone that simultaneously provides low-end foundation and midrange aggression.</p>

        <div className="mix-comparison-embed" aria-label="Interactive Bass Stem Comparison">
          <h3>Isolated Bass Stems Comparison</h3>
          <p className="embed-intro">Compare isolated bass processing to hear dynamic control, distortion techniques, and frequency management across producers.</p>
          <MixComparisonEmbed note={"Tip: Listen for compression consistency, distortion character, and low-end power."} mixes={[
        { src: "../assets/audio/stems/bass/himmp.mp3", name: "HiMMP Team", label: "HiMMP" },
        { src: "../assets/audio/stems/bass/bogren.mp3", name: "Jens Bogren", label: "Bogren" },
        { src: "../assets/audio/stems/bass/exeter.mp3", name: "Mike Exeter", label: "Exeter" },
        { src: "../assets/audio/stems/bass/getgood.mp3", name: "Adam 'Nolly' Getgood", label: "Getgood" },
        { src: "../assets/audio/stems/bass/middleton.mp3", name: "Josh Middleton", label: "Middleton" },
        { src: "../assets/audio/stems/bass/nordstrom.mp3", name: "Fredrik Nordström", label: "Nordström" },
        { src: "../assets/audio/stems/bass/odeholm.mp3", name: "Buster Odeholm", label: "Odeholm" },
        { src: "../assets/audio/stems/bass/otero.mp3", name: "Dave Otero", label: "Otero" },
        { src: "../assets/audio/stems/bass/scheps.mp3", name: "Andrew Scheps", label: "Scheps" }
      ]} waveformHeights={[47, 44, 42, 71, 63, 45, 85, 82, 66, 71, 77, 75, 57, 92, 81, 91, 92, 92, 92, 92, 74, 92, 66, 85, 92, 92, 92, 89, 92, 92, 64, 78, 85, 91, 60, 91, 71, 85, 86, 84, 75, 81, 57, 50, 75, 54, 54, 73]} />
        </div>

        <h2 id="practical-implementation">Practical Implementation</h2>
        <p>The research documented that regardless of philosophical approach, achieving heavy guitar and bass sounds involves addressing several universal challenges:</p>
        <ul>
          <li><strong>Palm-mute control:</strong> Managing the resonant booms that occur during chugging passages through multiband compression or dynamic EQ.</li>
          <li><strong>Frequency management:</strong> Ensuring kick, bass, and guitar spectra work together rather than competing, whether through regular EQ, multiband compression, or sidechaining.</li>
          <li><strong>Distortion management:</strong> Applying distortion strategically across frequency bands to maintain both clarity and aggression.</li>
          <li><strong>Dynamic consistency:</strong> Creating a stable foundation that maintains impact throughout varying performance intensities.</li>
        </ul>

        <p>The most successful productions addressed these challenges while maintaining the core musical identity of the material, using technology to enhance rather than override the compositional intent.</p>

                <blockquote className="pull-quote">
          <div className="pull-quote-content">
            <p>"I've found my sound, and I just want all my mixes to have the same quality and vibe. Tone‑matching ensures the bass guitar in this new song has a similar frequency balance to the bass on my other mixes."</p>
            <footer>— Buster Odeholm</footer>
          </div>
          <div className="pull-quote-photo">
            <img src="../assets/images/people/Odeholm.jpg" alt="Buster Odeholm" />
          </div>
        </blockquote>

        <aside className="sidebar-box">
          <strong>Call to Action 1</strong>
          <p>Explore the development of guitar and bass production techniques by comparing the isolated stems from different producers' mixes. Pay particular attention to how each producer balances low-end frequencies between kick, bass, and guitar, and how they manage midrange to prevent masking of other instruments.</p>
        </aside>

        <aside className="sidebar-box">
          <strong>Call to Action 2</strong>
          <p>Download the guitar and bass DIs from our research archive and experiment with different approaches to frequency allocation and dynamic management. Create one mix using traditional separation techniques and another using meta-instrument concepts, then compare the resulting heaviness and clarity.</p>
        </aside>

        <aside className="sidebar-box">
          <h3>Key Heuristics</h3>
          <ul>
            <li>Remember that perceived guitar heaviness often lives in the low-mid and midrange articulation, not just in extended low frequencies.</li>
            <li>Let bass and guitars share the low-end job intelligently: avoid duplicated energy that creates mud without adding weight.</li>
            <li>Shape distortion so that it supports note definition and rhythm, rather than turning everything into undifferentiated noise.</li>
            <li>Build your main rhythm sound in context with drums and vocals, not as a "perfect" isolated tone.</li>
            <li>Use dynamic tools (multiband compression, dynamic EQ, automation) to keep the wall of sound breathing and shifting with the arrangement.</li>
          </ul>
        </aside>

        <h2 id="endnotes">Endnotes</h2>
        <ol className="endnotes">
          <li id="endnote-1">Software plugins that replicate hardware amplifiers, cabinets, and microphones. <a className="backref" href="#ref-1">↩</a></li>
          <li id="endnote-2">Equalization with compression-like controls for specific frequency bands. <a className="backref" href="#ref-2">↩</a></li>
          <li id="endnote-3">Overlap with and obscure. <a className="backref" href="#ref-3">↩</a></li>
          <li id="endnote-4">Removing frequencies below a specific point. <a className="backref" href="#ref-4">↩</a></li>
          <li id="endnote-5">Recording and blending four takes of the same performance, two tracks per side. <a className="backref" href="#ref-5">↩</a></li>
          <li id="endnote-6">Processes that create perceived width beyond simple panning. <a className="backref" href="#ref-6">↩</a></li>
          <li id="endnote-7">A form of compression that prevents signals from exceeding a specified threshold. <a className="backref" href="#ref-7">↩</a></li>
          <li id="endnote-8">Higher-frequency overtones above the fundamental frequency. <a className="backref" href="#ref-8">↩</a></li>
        </ol>


        <p><a className="read-more" href="../audio.html">Access the Full Dataset &rarr;</a></p>

        <aside className="citation-box" aria-label="Citation and Licence">
          <strong>Citation</strong>
          <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
          <strong>Copyright &amp; Licence</strong>
          <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
        </aside>
        <div className="chapter-resources">
          <div className="container">
            <h3>Explore the Research</h3>
            <div className="resource-buttons">
              <a href="../audio.html" className="resource-button">Listen to Audio Examples</a>
              <a href="../videos.html" className="resource-button">Watch Producer Videos</a>
              <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer" className="resource-button">Download Full Dataset</a>
              <a href="../findings.html" className="resource-button">All Chapters</a>
            </div>
          </div>
        </div>

        <nav className="chapter-nav">
          <a className="prev-chapter" href="./08-drums.html">&larr; Prev: Ch. 8 Drum Production</a>
          <a className="all-chapters" href="../findings.html">Return to All Findings</a>
          <a className="next-chapter" href="./10-spatial.html">Next: Ch. 10 Spatial Dimensions &rarr;</a>
        </nav>
      </div>
    </section>
  <section className="content-section">
    <div className="container">
    </div>
  </section>
    </main>
  );
}
