/**
 * Findings chapter "03-methodology" — auto-generated by
 * `scripts/port-findings-chapters.mjs` from the legacy
 * `findings/03-methodology.html`. Do not hand-edit this file; rerun the
 * script after editing the legacy source. The script applies
 * mechanical JSX-safety conversions only (`class=` ->
 * `className=`, void-element self-close, kebab-case style ->
 * camelCase JSX style prop, `srcset=` -> `srcSet=`,
 * `for=` -> `htmlFor=`). Mix-comparison-player blocks are
 * additionally replaced with `<MixComparisonEmbed>` React
 * component calls (D-3-a) so the chapter audio surfaces own their
 * markup and state instead of relying on EnhancedAudioController's
 * post-hydration DOM walk.
 */
export type FindingsChapterHeading = { id: string; text: string };

/*
 * Chapter h2 headings, in document order. The D-8 within-chapter
 * TOC component (rendered by `EnhancedFindingsShell`) reads this
 * to emit `<nav aria-label="On this page">` for long chapters.
 * IDs match the values baked into the JSX below by `injectH2Ids`.
 */
export const FindingsChapter03Headings: FindingsChapterHeading[] = [
  { id: "the-test-track-in-solitude", text: "The Test Track: 'In Solitude'" },
  { id: "the-no-reference-mix-approach", text: "The \"No Reference Mix\" Approach" },
  { id: "data-collection-and-documentation-unprecedented-access", text: "Data Collection and Documentation: Unprecedented Access" }
];

export function FindingsChapter03() {
  return (
    <main id="main-content">
<section className="chapter-hero" style={{ backgroundImage: "url('Figures/0_Cover.jpg')", backgroundSize: "cover", backgroundPosition: "center", position: "relative" }}>
      <div className="hero-overlay"></div>
      <div className="container">
        <div className="hero-content">
          <h1 className="hero-title">Chapter 3: The Controlled Experiment</h1>
          <p className="hero-text">Method, the 'In Solitude' test track, and our no‑reference approach.</p>
        </div>
      </div>
    </section>
    <div className="chapter-section-nav">
      <div className="container">
        <h3>Navigate Chapters</h3>
        <div className="chapter-nav-buttons">
          <a href="./01-introduction.html" className="chapter-nav-button">Ch. 1</a>
          <a href="./02-producers.html" className="chapter-nav-button">Ch. 2</a>
          <a href="./03-methodology.html" className="chapter-nav-button active">Ch. 3</a>
          <a href="./04-foundations.html" className="chapter-nav-button">Ch. 4</a>
          <a href="./05-naturalistic.html" className="chapter-nav-button">Ch. 5</a>
          <a href="./06-hyperreal.html" className="chapter-nav-button">Ch. 6</a>
          <a href="./07-meta-instrument.html" className="chapter-nav-button">Ch. 7</a>
          <a href="./08-drums.html" className="chapter-nav-button">Ch. 8</a>
          <a href="./09-guitars-bass.html" className="chapter-nav-button">Ch. 9</a>
          <a href="./10-spatial.html" className="chapter-nav-button">Ch. 10</a>
          <a href="./11-subjective.html" className="chapter-nav-button">Ch. 11</a>
          <a href="./12-application.html" className="chapter-nav-button">Ch. 12</a>
          <a href="./13-future.html" className="chapter-nav-button">Ch. 13</a>
          <a href="./14-recommended-reading.html" className="chapter-nav-button">Ch. 14</a>
        </div>
      </div>
    </div>
    <section className="content-section">
      <div className="container chapter-content" style={{ "--chapter": "'3'" } as Record<string, string>}>
        <p>The 'Heaviness in Metal Music Production' (HiMMP) project was built on a unique principle: to gain practical insight into <em>how</em> top producers create heaviness, we had to eliminate all other variables. By providing identical, high-quality source material to eight producers, we established a controlled environment. This methodology allowed us to go beyond mere variations in recording quality or performance and discover the fundamental philosophical differences that drive metal production today.</p>

        <h2 id="the-test-track-in-solitude">The Test Track: 'In Solitude'</h2>
        <p>The experiment was based on 'In Solitude', a five-minute composition created specifically for this research.<sup id="ref-1"><a href="#endnote-1">1</a></sup> The song incorporated elements from various metal subgenres: it featured blast beats, technical sections, a half-time breakdown, and atmospheric passages. This varied arrangement provided producers with a comprehensive setup to demonstrate their approach to heaviness across different musical contexts.</p>
        <p>Following composition, the song was recorded professionally. The multi-track session<sup id="ref-2"><a href="#endnote-2">2</a></sup> provided to producers included:</p>
        <ul>
          <li>Complete drum recordings with both raw and time-aligned versions;</li>
          <li>MIDI trigger tracks<sup id="ref-3"><a href="#endnote-3">3</a></sup> for kick, snare, and toms;</li>
          <li>High-quality drum sample libraries<sup id="ref-4"><a href="#endnote-4">4</a></sup> created from the recording session;</li>
          <li>Multiple recording setups for all guitars and bass (different amplifiers and microphone combinations, see Figure 3.1);</li>
          <li>Additional direct injection (DI) tracks<sup id="ref-5"><a href="#endnote-5">5</a></sup> for re-amping<sup id="ref-6"><a href="#endnote-6">6</a></sup>;</li>
          <li>MIDI data for orchestral elements (strings, brass, synthesizers).</li>
        </ul>

        <p>This comprehensive package gave producers maximum flexibility to implement their vision while ensuring all artistic decisions resulted from production philosophy rather than source limitations.</p>
        <p>The complete dataset, including multi-track recordings (Figure 3.2), is available for research and educational purposes.<sup id="ref-7"><a href="#endnote-7">7</a></sup></p>

        <div className="figure figure-numbered">
          <img src="Figures/Fig3.1_Guitars.jpg" alt="Multiple microphone setups for the guitar recordings" loading="lazy" />
          <div className="figure-caption">Multiple microphone setups for the guitar recordings.</div>
        </div>

        <div className="figure figure-numbered">
          <img src="Figures/Fig3.2_Arrangement.png" alt="Multi-track of 'In Solitude' in Pro Tools; all tracks except toms and production FX" loading="lazy" />
          <div className="figure-caption">Multi-track of 'In Solitude' in Pro Tools; all tracks except toms and production FX.</div>
        </div>

        <p>Comparing these mixes is not intended as a competition. A closer examination of each mix instead demonstrates the production techniques that have proven effective for these eight highly respected, Grammy Award-winning producers, each bringing a unique sonic identity to their work. The approaches and methods that work for one producer may not necessarily apply to another. Each of these producers has developed a mixing methodology that succeeds within their own framework. The project aims to document and understand these different pathways to heaviness. Ranking them or determining which is "best" would miss the fundamental purpose of the research.</p>

        <h2 id="the-no-reference-mix-approach">The "No Reference Mix" Approach</h2>
        <p>A strategic decision involved providing no reference mix to the producers. While unconventional, this approach ensured each producer's mix represented their uninfluenced vision for how the song should sound. This methodology revealed stark differences and unprecedented insight into their conceptualization of heaviness that might have been obscured had producers been working toward a predetermined sonic blueprint.</p>

        <h2 id="data-collection-and-documentation-unprecedented-access">Data Collection and Documentation: Unprecedented Access</h2>
        <p>We collected multiple forms of data from each producer:</p>
        <ul>
          <li>Video recordings of mixing sessions;</li>
          <li>Semi-structured interviews exploring their conceptual understanding of heaviness;</li>
          <li>Detailed walkthroughs of their mixing decisions for 'In Solitude';</li>
          <li>Final stereo mixes and individual stem exports.<sup id="ref-8"><a href="#endnote-8">8</a></sup></li>
        </ul>
        <p>This multifaceted approach allowed us to compare and verify connections between what producers said about heaviness, how they actually implemented those concepts, and the sonic results of their work. In total, the project collected over 15 hours of video documentation, as well as eight complete mixes and 32 individual stem exports for comparative analysis.</p>
        <p>The full video documentation, including producer interviews and mixing session recordings, is available on the project's YouTube channel: <a href="https://www.youtube.com/@HiMMP-Research" target="_blank" rel="noopener noreferrer">https://www.youtube.com/@HiMMP-Research</a></p>

        <aside className="sidebar-box">
          <strong>Sidebar: The Controlled Variable Approach</strong>
          <p>While most music production research examines completed commercial releases, this study's original approach of having multiple producers mix identical material allowed for a direct comparison of production approaches. By controlling the "what" (the recorded material), the study isolated the "how" (production techniques) and "why" (conceptual understanding) to offer insights impossible to obtain through traditional methods.</p>
        </aside>

        <aside className="sidebar-box">
          <strong>Call to Action</strong>
          <p>Experience the methodology firsthand by downloading the multi-track session of 'In Solitude' and by watching the interview videos. Compare how different producers approached identical material and conduct your own mixing experiments to better understand the techniques discussed in this guide. The complete multi-track recording, final mixes, and stems are available for download here: <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer">HiMMP Research Dataset</a>.</p>
        </aside>

        <aside className="sidebar-box">
          <h3>Key Heuristics</h3>
          <ul>
            <li>Use controlled constraints (one song, fixed source material) to focus on what your production decisions actually change.</li>
            <li>Try mixing the same multitracks in several ways (more Naturalistic, more Hyperreal) to expose your own habits and blind spots.</li>
            <li>Occasionally work without a reference mix to hear what you naturally gravitate towards, then compare against references to calibrate.</li>
            <li>Document your decisions and outcomes; treat each mix as an experiment you can learn from, not just a one-off product.</li>
          </ul>
        </aside>

        <h2 id="endnotes">Endnotes</h2>
        <ol className="endnotes">
          <li id="endnote-1">You can listen to our own mix of 'In Solitude' on Spotify: <a href="https://open.spotify.com/track/3qk8nfMpCTLHtGSew8oD7O?si=dc064f8fa2fb4bfd" target="_blank" rel="noopener noreferrer">https://open.spotify.com/track/3qk8nfMpCTLHtGSew8oD7O?si=dc064f8fa2fb4bfd</a> <a className="backref" href="#ref-1">↩</a></li>
          <li id="endnote-2">A project within a digital audio workstation that allows processing on individual tracks of a recording. <a className="backref" href="#ref-2">↩</a></li>
          <li id="endnote-3">A digital protocol for communication between instruments and computers. <a className="backref" href="#ref-3">↩</a></li>
          <li id="endnote-4">Pre-recorded and sometimes pre-mixed recordings of individual drum shells or cymbals. <a className="backref" href="#ref-4">↩</a></li>
          <li id="endnote-5">Recordings of electronic instruments directly into a sound card or mixing device. <a className="backref" href="#ref-5">↩</a></li>
          <li id="endnote-6">A technique that allows re-recording an already recorded performance using different amplifiers or recording chains. <a className="backref" href="#ref-6">↩</a></li>
          <li id="endnote-7">All materials can be accessed here: <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer">https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur</a> <a className="backref" href="#ref-7">↩</a></li>
          <li id="endnote-8">Sub-mixes of instrument groups such as drums, bass, guitars, and vocals. <a className="backref" href="#ref-8">↩</a></li>
        </ol>

        <aside className="citation-box" aria-label="Citation and Licence">
          <strong>Citation</strong>
          <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
          <strong>Copyright &amp; Licence</strong>
          <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
        </aside>
        <div className="chapter-resources">
          <div className="container">
            <h3>Explore the Research</h3>
            <div className="resource-buttons">
              <a href="../audio.html" className="resource-button">Listen to Audio Examples</a>
              <a href="../videos.html" className="resource-button">Watch Producer Videos</a>
              <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer" className="resource-button">Download Full Dataset</a>
              <a href="../findings.html" className="resource-button">All Chapters</a>
            </div>
          </div>
        </div>

        <nav className="chapter-nav">
          <a className="prev-chapter" href="./02-producers.html">← Prev: Ch. 2 The Masters of Metal</a>
          <a className="all-chapters" href="../findings.html">Return to All Findings</a>
          <a className="next-chapter" href="./04-foundations.html">Next: Ch. 4 Shared Foundations →</a>
        </nav>
      </div>
    </section>
  <section className="content-section">
    <div className="container">
    </div>
  </section>
    </main>
  );
}
