/**
 * Findings chapter "10-spatial" — auto-generated by
 * `scripts/port-findings-chapters.mjs` from the legacy
 * `findings/10-spatial.html`. Do not hand-edit this file; rerun the
 * script after editing the legacy source. The script applies
 * mechanical JSX-safety conversions only (`class=` ->
 * `className=`, void-element self-close, kebab-case style ->
 * camelCase JSX style prop, `srcset=` -> `srcSet=`,
 * `for=` -> `htmlFor=`). Mix-comparison-player blocks are
 * additionally replaced with `<MixComparisonEmbed>` React
 * component calls (D-3-a) so the chapter audio surfaces own their
 * markup and state. D-3-b retired the controller; nothing
 * DOM-walks chapter audio surfaces any more.
 */
import { MixComparisonEmbed } from "@/src/site/components/MixComparisonEmbed";

export type FindingsChapterHeading = { id: string; text: string };

/*
 * Chapter h2 headings, in document order. The D-8 within-chapter
 * TOC component (rendered by `EnhancedFindingsShell`) reads this
 * to emit `<nav aria-label="On this page">` for long chapters.
 * IDs match the values baked into the JSX below by `injectH2Ids`.
 */
export const FindingsChapter10Headings: FindingsChapterHeading[] = [
  { id: "width-beyond-pan-positions", text: "Width: Beyond Pan Positions" },
  { id: "depth-from-in-your-face-to-three-dimensional", text: "Depth: From In-Your-Face to Three-Dimensional" }
];

export function FindingsChapter10() {
  return (
    <main id="main-content">
<section className="chapter-hero" style={{ backgroundImage: "url('Figures/0_Cover.jpg')", backgroundSize: "cover", backgroundPosition: "center", position: "relative" }}>
      <div className="hero-overlay"></div>
      <div className="container">
        <div className="hero-content">
          <h1 className="hero-title">Chapter 10: Spatial Dimensions of Heaviness</h1>
          <p className="hero-text">Width, depth, and immersion in heavy production.</p>
        </div>
      </div>
    </section>
    <div className="chapter-section-nav">
      <div className="container">
        <h3>Navigate Chapters</h3>
        <div className="chapter-nav-buttons">
          <a href="./01-introduction.html" className="chapter-nav-button">Ch. 1</a>
          <a href="./02-producers.html" className="chapter-nav-button">Ch. 2</a>
          <a href="./03-methodology.html" className="chapter-nav-button">Ch. 3</a>
          <a href="./04-foundations.html" className="chapter-nav-button">Ch. 4</a>
          <a href="./05-naturalistic.html" className="chapter-nav-button">Ch. 5</a>
          <a href="./06-hyperreal.html" className="chapter-nav-button">Ch. 6</a>
          <a href="./07-meta-instrument.html" className="chapter-nav-button">Ch. 7</a>
          <a href="./08-drums.html" className="chapter-nav-button">Ch. 8</a>
          <a href="./09-guitars-bass.html" className="chapter-nav-button">Ch. 9</a>
          <a href="./10-spatial.html" className="chapter-nav-button active">Ch. 10</a>
          <a href="./11-subjective.html" className="chapter-nav-button">Ch. 11</a>
          <a href="./12-application.html" className="chapter-nav-button">Ch. 12</a>
          <a href="./13-future.html" className="chapter-nav-button">Ch. 13</a>
          <a href="./14-recommended-reading.html" className="chapter-nav-button">Ch. 14</a>
        </div>
      </div>
    </div>
    <section className="content-section">
      <div className="container chapter-content" style={{ "--chapter": "'10'" } as Record<string, string>}>
        <p>While previous sections have addressed tonal, dynamic, and technical elements of heaviness, this section explores an often-overlooked dimension: how spatial characteristics shape the listener’s perception. The research documented distinct approaches to spatial design that significantly impact the effectiveness of heavy productions.</p>

        <h2 id="width-beyond-pan-positions">Width: Beyond Pan Positions</h2>
        <p>All producers employed stereo techniques to sculpt width, but with different approaches and philosophical underpinnings:</p>
        <ul>
          <li><strong>Traditional Hard-Panning</strong>: The foundational approach to width in metal involves hard-panning rhythm guitars left and right. This technique, dating back to early metal productions, creates a wide stereo field while maintaining a strong centre presence through kick, snare, bass, and vocals. Jens Bogren, representing the traditional Swedish death metal sound, maintained this approach with minimal embellishment, creating a classic metal wall of guitars.</li>
          <li><strong>Enhanced Psychoacoustic Width</strong>: Several producers chose sophisticated techniques to create width beyond what simple panning permits. Adam Getgood and Josh Middleton utilized stereo enhancement plugins<sup id="ref-1"><a href="#endnote-1">1</a></sup> that create phase differences between channels, resulting in a perceived width that exceeds the physical speaker placement. Middleton described the outcome as extending beyond the speakers to create an enveloping experience that surrounds the listener.</li>
          <li><strong>Asymmetrical EQ Approach</strong>: Notably, the research found that Andrew Scheps and Mike Exeter achieved comparable width through a more transparent technique: applying slightly different equalization to left and right guitar channels. The brain perceives even subtle frequency imbalances between channels as increased width. This approach maintains phase coherence while still creating the impression of guitars extending beyond speaker boundaries.</li>
          <li><strong>Extended Bass Width</strong>: Odeholm's application of the meta-instrument concept to spatial design (as described in <a href="./07-meta-instrument.html">Chapter 7</a>) represents perhaps the most radical departure from convention. His stereo bass approach created a distinct spatial configuration where traditional instrument roles are inverted: bass contributes to width while guitars reinforce central impact.</li>
        </ul>
        <p>Analysis of the ‘In Solitude’ suggests multiple valid paths to creating spatial staging, each with distinct tonal and phase characteristics.</p>

        <div className="mix-comparison-embed" aria-label="Interactive Mix Comparison">
          <h3>Interactive Mix Comparison</h3>
          <p className="embed-intro">Compare stereo width and perceived depth between producers.</p>
          <MixComparisonEmbed note={"Tip: Listen on headphones, then speakers, for spatial contrast."} mixes={[
        { src: "../assets/audio/HiMMP.mp3", name: "HiMMP Team", label: "HiMMP" },
        { src: "../assets/audio/Bogren.mp3", name: "Jens Bogren", label: "Bogren" },
        { src: "../assets/audio/Exeter.mp3", name: "Mike Exeter", label: "Exeter" },
        { src: "../assets/audio/Getgood.mp3", name: "Adam ‘Nolly’ Getgood", label: "Getgood" },
        { src: "../assets/audio/Middleton.mp3", name: "Josh Middleton", label: "Middleton" },
        { src: "../assets/audio/Nordstrom.mp3", name: "Fredrik Nordström", label: "Nordström" },
        { src: "../assets/audio/Odeholm.mp3", name: "Buster Odeholm", label: "Odeholm" },
        { src: "../assets/audio/Otero.mp3", name: "Dave Otero", label: "Otero" },
        { src: "../assets/audio/Scheps.mp3", name: "Andrew Scheps", label: "Scheps" }
      ]} waveformHeights={[69, 40, 59, 50, 46, 67, 62, 84, 62, 85, 76, 72, 90, 78, 73, 92, 78, 65, 92, 80, 92, 70, 92, 66, 88, 69, 81, 73, 69, 86, 68, 92, 83, 77, 89, 76, 62, 60, 74, 92, 51, 79, 59, 46, 79, 53, 78, 72]} />
        </div>

        <p>Now that we have explored the various approaches to stereo width, let us turn our attention to the vertical dimension of the soundstage: depth.</p>

        <h2 id="depth-from-in-your-face-to-three-dimensional">Depth: From In-Your-Face to Three-Dimensional</h2>
        <p>The research identified depth perception as a central yet often overlooked dimension of heaviness, with approaches falling into several overlapping categories (Figures 10.1–10.2):</p>
        <ul>
          <li><strong>Immersive Depth Staging</strong>: Several producers including Andrew Scheps employed a virtual soundstage concept where instruments occupy distinct positions in a three-dimensional space. In Scheps’s mix, backing vocals were positioned deep in the soundstage while lead elements remained upfront. This creates a believable space where the band exists, which enhances the perceived authenticity and depth of the production. This approach aligns with traditional rock production values, where creating a realistic performance space enhances listener engagement.</li>
          <li><strong>Controlled Ambient Space</strong>: Jens Bogren and Mike Exeter created depth through selective reverb application, using multiple ambient layers. Bogren used up to four different reverbs on drums alone, each tailored to specific elements but sharing complementary characteristics. This creates the impression of a cohesive space while maintaining separation between elements. Significantly, even these ambient-aware producers kept reverb times relatively short (typically under 1.5 seconds) to maintain impact and clarity.</li>

        <aside className="sidebar-box">
          <strong>Sidebar: Reverb as a Strategic Tool</strong>
          <p>Unlike many genres where reverb primarily creates space, metal producers use it as a strategic effect. The research found that even "dry" metal productions typically employ multiple short reverbs (under 1.5s), often frequency-specific and heavily controlled. Bogren used up to four different reverbs on drums alone, each serving a specific purpose, from attack enhancement to sustain extension, while always avoiding mud in the critical low-mid range.</p>
        </aside>

          <li><strong>Hyperreal Flatness</strong>: At the opposite extreme, Buster Odeholm minimized depth cues to create a direct transmission to the listener. By keeping elements extremely dry<sup id="ref-2"><a href="#endnote-2">2</a></sup> and upfront in the mix, he created the sensation of the sound bypassing space entirely; it is as if the instruments are physically present in the listener's space rather than captured in a recording. This approach sacrifices spatial realism for maximum impact and creates the impression of being physically confronted by sound.</li>
        </ul>

        <div className="figure figure-numbered">
          <img src="Figures/Fig10.1_Soundstage1.png" alt="Soundstage visualization of the mixes of Bogren, Exeter, Getgood, and Middleton" loading="lazy" />
          <div className="figure-caption">Soundstage visualization of the mixes of Bogren, Exeter, Getgood, and Middleton. The soundstage represents stereo width and depth dimension. Height (frequency ranges) is not displayed.</div>
        </div>
        <div className="figure figure-numbered">
          <img src="Figures/Fig10.2_Soundstage2.png" alt="Soundstage visualization of the mixes of Nordström, Odeholm, Otero, and Scheps" loading="lazy" />
          <div className="figure-caption">Soundstage visualization of the mixes of Nordström, Odeholm, Otero, and Scheps.</div>
        </div>

        <p>The analysis suggested that depth perception influences how listeners experience the characteristics of the mix, including the perception of heaviness. Three-dimensional mixes create heaviness through immersion and scale, while flattened presentations ("in your face") achieve it through directness and confrontation. Both approaches prove effective but engage listeners in different ways.</p>

        <aside className="sidebar-box">
          <strong>Call to Action 1</strong>
          <p>Compare the spatial characteristics of each producer's mix by listening with headphones, then on speakers. Notice how different approaches to width, depth, and ambience affect your perception of heaviness. Try implementing these spatial techniques in your own productions to achieve the balance of power and immersion that best serves your musical vision.</p>
        </aside>

        <aside className="sidebar-box">
          <strong>Call to Action 2</strong>
          <p><a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer">Download the multi-track of 'In Solitude' from our archive</a> and apply different spatial processing to enhance or reduce depth. Create three versions: one with traditional stereo width only, another with enhanced psychoacoustic width, and a third with additional depth through carefully crafted reverb. Listen to all three in different environments (headphones, speakers, car) to understand how spatial characteristics translate across listening scenarios.</p>
        </aside>

        <aside className="sidebar-box">
          <h3>Key Heuristics</h3>
          <ul>
            <li>Treat width and depth as part of heaviness: a mix can feel crushingly close, cavernously vast, or both by contrast.</li>
            <li>Keep the lowest frequencies largely mono and centred, building width from higher-frequency elements and ambience.</li>
            <li>Use reverbs, delays, and room mics to place elements at specific depths, but watch that cumulative ambience does not blur transients.</li>
            <li>Make deliberate decisions about listener position (on stage, in the pit, in the control room) and let this guide panning, ambience, and front-back placement.</li>
            <li>Regularly check the mix in mono and at lower levels to ensure spatial decisions survive translation.</li>
          </ul>
        </aside>

        <h2 id="endnotes">Endnotes</h2>
        <ol className="endnotes">
          <li id="endnote-1">Processors that create phase differences between channels. <a className="backref" href="#ref-1">↩</a></li>
          <li id="endnote-2">With minimal or no effects applied. <a className="backref" href="#ref-2">↩</a></li>
        </ol>

        <aside className="citation-box" aria-label="Citation and Licence">
          <strong>Citation</strong>
          <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
          <strong>Copyright &amp; Licence</strong>
          <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
        </aside>
        <div className="chapter-resources">
          <div className="container">
            <h3>Explore the Research</h3>
            <div className="resource-buttons">
              <a href="../audio.html" className="resource-button">Listen to Audio Examples</a>
              <a href="../videos.html" className="resource-button">Watch Producer Videos</a>
              <a href="https://huddersfield.app.box.com/s/8gren2ma4kesvf5vwip2axzz1v8sawur" target="_blank" rel="noopener noreferrer" className="resource-button">Download Full Dataset</a>
              <a href="../findings.html" className="resource-button">All Chapters</a>
            </div>
          </div>
        </div>

        <nav className="chapter-nav">
          <a className="prev-chapter" href="./09-guitars-bass.html">&larr; Prev: Ch. 9 Guitar &amp; Bass Engineering</a>
          <a className="all-chapters" href="../findings.html">Return to All Findings</a>
          <a className="next-chapter" href="./11-subjective.html">Next: Ch. 11 Subjective Dimensions &rarr;</a>
        </nav>
      </div>
    </section>
  <section className="content-section">
    <div className="container">
    </div>
  </section>
    </main>
  );
}
