/**
 * Findings index page (`/findings`) — eleventh page port.
 *
 * The page is wrapped by `<EnhancedFindingsShell>` (the same shell
 * the catch-all wraps around findings routes via the
 * `enhanced-findings` renderMode). The shell adds a sidebar/topbar
 * chapter navigator and a reader-panel overlay. Wrapping is done
 * in the route file (`app/findings/page.tsx`), not here.
 *
 * Body generated by `scripts/port-findings-index.mjs`. The script
 * applies these mechanical swaps:
 *
 * - `class=` -> `className=`
 * - `for=` -> `htmlFor=`
 * - `<br>` / `<hr>` / `<input ...>` / `<source ...>` ->
 *   self-closed JSX void forms
 * - `srcset=` -> `srcSet=` (React's prop name)
 * - inline `style="kebab-case: val"` -> JSX `style={{ camel: "val" }}`
 *
 * One structural fix: the legacy `findings.html` lines 303-310 are
 * malformed — the Acknowledgements block starts with a raw
 * `<div class="container">` and ends with an orphan `</section>`
 * that has no matching open. Browsers parse leniently, but JSX
 * requires balanced tags. The script inserts the missing
 * `<section class="content-section">` open. Visible text is
 * unchanged; `parity:text` confirms.
 */
export function FindingsIndexPage() {
  return (
    <main id="main-content">
      <section
        className="hero"
        style={{
          backgroundImage: "url('findings/Figures/0_Cover.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          position: "relative"
        }}
      >
        <div className="hero-overlay"></div>
        <div className="container">
          <div className="hero-content">
            <h1 className="hero-title">Heaviness in Metal Music Production: A Practical Guide</h1>
            <p className="hero-text"><strong><em>Primarily written for metal producers, mix engineers, and advanced home recordists working in heavy music.</em></strong><br />This is where our research becomes your practical toolkit. Drawing on the 'Heaviness in Metal Music Production' (HiMMP) project, it distils our findings into an applied guide for contemporary metal production. You can read it on its own or alongside the project’s full dataset, videos, and publications at <a href="https://www.himmp.net">www.himmp.net</a>. Go hands-on with the core philosophies and technical analyses from our study; audio examples are provided throughout.</p>
          </div>
        </div>
      </section>
<section className="content-section">
            <div className="container">
                <h2>What Really Creates Heaviness?</h2>
        
                <p>Our research suggests that 'heaviness' is not one single sound; it is the result of a producer's core philosophy. We found these approaches exist on a spectrum: from the 'Naturalistic' approach (focused on capturing organic performance) to the 'Hyperreal' approach (engineering a 'larger-than-life' sound). This guide breaks down our findings chapter by chapter, with practical examples and audio from the project.</p>

                <div className="figure" style={{ marginTop: "1rem" }}>
                    <img src="findings/Figures/0_Cover3.png" alt="Key Findings cover artwork for Deconstructing 'Heaviness'" loading="lazy" />
                    <div className="figure-caption">Key Findings: A Practical Guide</div>
                </div>


                <div className="info-box">
                <h3>Newer to production?</h3>
                <p>
                    If you are relatively new to recording or mixing heavy music, you may find it helpful 
                    to skim the <a href="findings/glossary.html"><strong>Glossary</strong></a> first, especially 
                    the entries on <em>transient</em>, <em>phase alignment</em>, <em>meta-instrument</em>, 
                    <em>bleed</em>, and <em>bus compression</em>. Having these concepts in mind will make 
                    the rest of the guide easier to follow.
                </p>
                <p>
                    More experienced producers and mix engineers can jump straight into the chapters 
                    and refer back to the Glossary as needed.
                </p>
                </div>

                <h3>Video Walkthroughs and Mix Comparisons</h3>
                <p>Alongside this written guide, the <strong>Heaviness in Metal Music Production (HiMMP)</strong> project provides extensive video material on the <em>HiMMP-Research</em> YouTube channel. These videos complement the chapters here and allow you to see and hear many of the concepts in practice.</p>
                <ul>
                    <li><strong>Conceptual interviews</strong>: in-depth conversations with each of the eight producers about their philosophies of heaviness, workflows, and production decisions.</li>
                    <li><strong>Mix documentation sessions</strong>: screen-captured walkthroughs of the actual 'In Solitude' mixes, showing how drums, guitars, bass, vocals, and effects were shaped in the DAW.</li>
                    <li><strong>Researchers' mix comparison video</strong>: a systematic comparison of all eight mixes, highlighting contrasting production approaches to the same source material.</li>
                </ul>
                <p>If you prefer to learn by watching and listening, or you want to connect specific techniques in this guide to real session workflows, use these videos as a parallel resource. You can find them on the <a href="https://www.youtube.com/@HiMMP-Research" target="_blank" rel="noopener noreferrer"><strong>HiMMP-Research YouTube channel</strong></a> or by following the video links provided on <a href="https://himmp.net" target="_blank" rel="noopener noreferrer"><strong>himmp.net</strong></a>.</p>

                <div className="chapters-grid">
                    <div className="chapter-card">
                        <h3>1. The Pursuit of Heaviness</h3>
                        <p>Start here. We trace metal's sonic journey and introduce the 'Natural vs. Hyperreal' debate at the heart of our study.</p>
                        <p><a href="./findings/01-introduction.html">Read Chapter 1 &rarr;</a></p>
                    </div>
                    
                    <div className="chapter-card">
                        <h3>2. The Masters of Metal</h3>
                        <p>Meet the eight world-class producers who participated in the study, from genre veterans like Mike Exeter to modern innovators like Buster Odeholm.</p>
                        <p><a href="./findings/02-producers.html">Read Chapter 2 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>3. The Controlled Experiment</h3>
                        <p>See how we designed the experiment, from creating the 'In Solitude' test track to our 'no reference mix' approach.</p>
                        <p><a href="./findings/03-methodology.html">Read Chapter 3 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>4. Shared Foundations of Heaviness</h3>
                        <p>What do all eight producers agree on? Explore the nature of heaviness and the 'Slow, Low, and Dense' formula.</p>
                        <p><a href="./findings/04-foundations.html">Read Chapter 4 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>5. The Naturalistic Approach</h3>
                        <p>A deep dive into 'organic heaviness.' Learn the philosophy that prioritizes performance capture and human feel.</p>
                        <p><a href="./findings/05-naturalistic.html">Read Chapter 5 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>6. The Hyperreal Approach</h3>
                        <p>Explore 'engineered extremity', the philosophy of using technology to create a sound that is tighter and more powerful than reality.</p>
                        <p><a href="./findings/06-hyperreal.html">Read Chapter 6 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>7. The "Meta-Instrument" Concept</h3>
                        <p>Discover our central finding: how modern producers treat the kick and bass, along with the guitars, as one unified sonic force.</p>
                        <p><a href="./findings/07-meta-instrument.html">Read Chapter 7 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>8. Drum Production</h3>
                        <p>A technical breakdown of sample use and transient design, showing how they create foundational impact.</p>
                        <p><a href="./findings/08-drums.html">Read Chapter 8 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>9. Guitar &amp; Bass Engineering</h3>
                        <p>An analysis of low-end management and dynamic EQ, exploring the 'wall of sound' in guitar and bass processing.</p>
                        <p><a href="./findings/09-guitars-bass.html">Read Chapter 9 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>10. Spatial Dimensions of Heaviness</h3>
                        <p>How producers use width and depth to create immersion, from 'in-your-face' to 'in-the-room'.</p>
                        <p><a href="./findings/10-spatial.html">Read Chapter 10 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>11. Subjective Dimensions of Heaviness</h3>
                        <p>Why do we perceive heaviness differently? An exploration of listening history and evolving perceptual standards.</p>
                        <p><a href="./findings/11-subjective.html">Read Chapter 11 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>12. Application Guide: Choosing Your Approach</h3>
                        <p>Put it all to work. This is your guide to assessing musical context and choosing the right techniques for your own productions.</p>
                        <p><a href="./findings/12-application.html">Read Chapter 12 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>13. Future Directions: The Evolving Pursuit</h3>
                        <p>Our concluding thoughts on the future of heaviness and the fundamentals that will always define metal.</p>
                        <p><a href="./findings/13-future.html">Read Chapter 13 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>14. Recommended Reading</h3>
                        <p>Essential reading on heaviness in metal music production: the HiMMP volumes, foundational research, and further resources.</p>
                        <p><a href="./findings/14-recommended-reading.html">Read Chapter 14 &rarr;</a></p>
                    </div>
                    <div className="chapter-card">
                        <h3>Glossary of Technical Terms</h3>
                        <p>Your quick-reference for all the production terms used in our guide.</p>
                        <p><a href="./findings/glossary.html">Open Glossary &rarr;</a></p>
                    </div>
                </div>
            </div>
        </section>

        <section className="content-section">
            <div className="container">
                <h2>About the Authors</h2>

                <div className="author-bio">
                    <div className="figure portrait">
                        <picture>
                            <source srcSet="assets/images/people/Herbst.webp" type="image/webp" />
                            <img src="assets/images/people/Herbst.jpg" alt="Portrait of Jan-Peter Herbst" loading="lazy" />
                        </picture>
                        <div className="figure-caption">Jan-Peter Herbst</div>
                    </div>
                    <p><strong>Jan-Peter Herbst</strong> is Professor of Music at the University of Huddersfield. His work focuses on popular music studies, music production, and especially the aesthetics and cultures of rock and metal. He leads several funded research projects, including <em>Heaviness in Metal Music Production</em>, and is editor of <em>The Cambridge Companion to Metal Music</em> (2023) and co-author of <em>Heaviness in Metal Music Production, Volumes I and II</em>.</p>
                </div>

                <div className="author-bio">
                    <div className="figure portrait">
                        <picture>
                            <source srcSet="assets/images/people/Mynett.webp" type="image/webp" />
                            <img src="assets/images/people/Mynett.jpg" alt="Portrait of Mark Mynett" loading="lazy" />
                        </picture>
                        <div className="figure-caption">Mark Mynett</div>
                    </div>
                    <p><strong>Mark Mynett</strong> is Senior Lecturer in Music Technology and Production at the University of Huddersfield, as well as a record producer, recording–mixing–mastering engineer, and live sound engineer. He runs the studio Mynetaur Productions and has an extensive background as a professional metal guitarist, including international releases and touring with Kill II This. He is the author of <em>Metal Music Manual</em> (2017) and co-author of <em>Heaviness in Metal Music Production, Volumes I and II</em>.</p>
                </div>
            </div>
        </section>

        <section className="content-section">
            <div className="container">
                <aside className="citation-box" aria-label="Citation and Licence">
                  <strong>Citation</strong>
                  <p>Please cite as: Jan-Peter Herbst &amp; Mark Mynett (2025). <em>Heaviness in Metal Music Production: A Practical Guide</em>. Self-Published, <a href="https://himmp.net" target="_blank" rel="noopener noreferrer">www.himmp.net</a>. DOI: <a href="https://doi.org/10.5281/zenodo.17608064" target="_blank" rel="noopener noreferrer">10.5281/zenodo.17608064</a>.</p>
                  <strong>Copyright &amp; Licence</strong>
                  <p>© 2025 Jan-Peter Herbst and Mark Mynett. Licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">Creative Commons Attribution (CC BY 4.0)</a>. You are free to share and adapt the material for any purpose, provided appropriate credit is given.</p>
                </aside>
            </div>
        </section>
            <section className="content-section">
<div className="container">
                <h2>Acknowledgements</h2>
                <p><strong>Acknowledgements:</strong> Funded by the Arts and Humanities Research Council (AHRC), grant AH/T010991/1. With gratitude to the University of Huddersfield (SAH and SCE).</p>
                <p><strong>Editorial Note:</strong> We used AI-assisted tools (Grammarly Pro, EditGPT Pro, Google Gemini Advanced 2.5) for copyediting and structural suggestions. All analysis, interpretation, and editorial decisions are our own.</p>
                <p><a className="read-more" href="./acknowledgements.html">Read Full Acknowledgements &rarr;</a></p>
            </div>
        </section>

        <section className="content-section">
            <div className="container" style={{ textAlign: "center" }}>
                <h2>Ready to Listen for Yourself?</h2>
                <p>Reading is one thing; hearing is believing. All the mixes and stems, plus the raw multitracks, are available for free. Download the data, compare the results, and try mixing 'In Solitude' yourself.</p>
                <a className="read-more" href="./audio.html">Access the Full Dataset &rarr;</a>
            </div>
        </section>
    </main>
  );
}
